### ISSUE TITLE
TypeError: val[key].map is not a function at cast$expr.js:102:27

### ISSUE THREAD

**Issue by rwmia** [Automattic/mongoose#11689]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behavior?**
Getting an error when querying. TypeError: val[key].map is not a function at _castExpression (/opt/nodejs/node_modules/mongoose/lib/helpers/query/cast$expr.js:102:27)

**If the current behavior is a bug, please provide the steps to reproduce.**
When updating to 6.3 I started to get the error. I believe it may be this expression in my query below. If there is a better way to write the expression to avoid the casting error, if not a bug, please let me know.

```
$expr: {
          $not: {
            $in: [{
              email_id: mongoose.Types.ObjectId(email._id),
              upcoming_date: '$date_end'
            }, '$last_upcoming_notifications']
          }
 }
```

**What is the expected behavior?**
Hopefully not error :)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14 (AWS Lambda)
Mongoose 6.3.0
MongoDB Atlas 4.4.13

**Comment by Uzlopak** [comment]
It seems that mongoose expects that $not is an Array. But $not is expecting an expression not an Array. 

Probably it is solved by movng the $not operator from booleanComparison to comparisonOperator. Or by adding a isArray-Check after `if (booleanComparison.has(key)`

**Comment by rwmia** [comment]
Yea the .map is causing the error, expecting an array. I have modified with:
if (booleanComparison.has(key)) {
      if (Array.isArray(val[key])) {
        val[key] = val[key].map(v => _castExpression(v, schema, strictQuery));
      }
    }

Perhaps at some point there can be a global option to not cast $expr? I.e. mongoose.set('castExpr', false);
