### ISSUE TITLE
migrate from node v0.10.36 -> v0.12.4 crash

### ISSUE THREAD

**Issue by b96705008** [Automattic/mongoose#3072]
We create a website using the node + mongoose, and it works fine in node v0.10.36. After we upgrade the node to v0.12.4, and start the app, open the web to load static file, the server crash. The error stack is below: 

/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: object is not a function
    at IncomingMessage._dump (_http_incoming.js:194:10)
    at ServerResponse.resOnFinish (_http_server.js:465:13)
    at ServerResponse.emit (events.js:104:17)
    at ServerResponse.OutgoingMessage._finish (_http_outgoing.js:572:8)
    at ServerResponse._finish (_http_server.js:118:37)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:563:10)
    at ServerResponse.res.end (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/compression/index.js:98:20)
    at writeend (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/express-session/index.js:224:14)
    at onsave (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/express-session/index.js:290:11)
    at /Users/roger19890107/Developer/projectData/projects/himelight/node_modules/connect-mongo/lib/connect-mongo.js:361:9
    at handleCallback (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/lib/collection.js:659:5
    at /Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:795:13
    at Callbacks.emit (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at null.messageHandler (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/Users/roger19890107/Developer/projectData/projects/himelight/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
[nodemon] app crashed - waiting for file changes before starting...

Is there already any solution to this problem?

**Comment by b96705008** [comment]
We use the mongoose 4.0.5

**Comment by vkarpov15** [comment]
Looks like the issue is in connect-mongo, not terribly surprising. I would strongly recommend not using connect-mongo. Use https://www.npmjs.com/package/connect-mongodb-session instead.
