### ISSUE TITLE
TypeScript Regression: deleteMany, deleteOne, replaceOne, updateMany, updateOne no longer support arbitrary options

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#14341]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.1

### Node.js version

18.18.2

### MongoDB server version

5

### Typescript version (if applicable)

4.8.3

### Description

Some of my custom plugins rely on parameters being passed to operations, like so:

```typescript
await MyModel.updateMany(
    {},
    {
        $set: {
            a: "a"
        }
    },
    {
        disableAutoSession: true // <--- compilation error here
    }
);
```

After migrating from 7.6.7 to 8.1.1 this no longer compiles. This is true for deleteMany, deleteOne, replaceOne, updateMany and updateOne. Other methods, e.g. findOneAndDelete still accept arbitrary options:

```typescript
await MyModel.findOneAndDelete(
    {},
    {
        disableAutoSession: true // <--- this is fine
    }
);
```

The corresponding Document methods (deleteOne, replaceOne, updateOne) accept arbitrary parameters as well.

### Steps to Reproduce

See description.

**Comment by FaizBShah** [comment]
@juona The reason for this is because in functions like [`updateMany`](https://github.com/Automattic/mongoose/blob/master/types/models.d.ts#L735), the typing of the `options` parameter contains [`MongooseQueryOptions<TRawDocType>`](https://github.com/Automattic/mongoose/blob/master/types/query.d.ts#L20) instead of [`QueryOptions<TRawDocType>`](https://github.com/Automattic/mongoose/blob/master/types/query.d.ts#L113) which is present in a function like [`findOneAndDelete`](https://github.com/Automattic/mongoose/blob/master/types/models.d.ts#L638). Now, the difference between the two is that `MongooseQueryOptions<T>` does not contain the field [`[other: string]: any;`](https://github.com/Automattic/mongoose/blob/master/types/query.d.ts#L192) which is required for allowing other arbitary fields in the options object.

**Comment by FaizBShah** [comment]
@vkarpov15 We can fix this by modifying this existing line:
```
options?: (mongodb.UpdateOptions & Omit<MongooseQueryOptions<TRawDocType>, 'lean'>) | null
```
to this:
```
options?: (mongodb.UpdateOptions & Omit<MongooseQueryOptions<TRawDocType>, 'lean'> & { [other: string]: any; }) | null
```

We can also add this field in MongooseQueryOptions, but Im not sure whether that will be a good choice

**Comment by FaizBShah** [comment]
@vkarpov15 Can I create a PR for this to fix this? I actually started contributing to open-source, and just want to be a good devloper :D

**Comment by vkarpov15** [comment]
@FaizBShah sure. I'd recommend adding `[other: string]: any;` to `MongooseQueryOptions` so this change applies to all affected methods.

**Comment by vkarpov15** [comment]
Fixed by #14342
