### ISSUE TITLE
FilterQuery Typing fails for generic type

### ISSUE THREAD

**Issue by david-loe** [Automattic/mongoose#14459]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.3

### Node.js version

20

### MongoDB server version

7.0.6

### Typescript version (if applicable)

5.4.3

### Description

Repro Script throws
```
No overload matches this call.
  Overload 1 of 5, '(filter: FilterQuery<ModelType>, projection?: ProjectionType<ModelType> | null | undefined, options?: QueryOptions<ModelType> | null | undefined): Query<...>', gave the following error.
    Argument of type '{ _id: string | Types.ObjectId; }' is not assignable to parameter of type 'FilterQuery<ModelType>'.
      Type '{ _id: string | Types.ObjectId; }' is not assignable to type '{ [P in keyof ModelType]?: Condition<ModelType[P]> | undefined; }'.
  Overload 2 of 5, '(filter: FilterQuery<ModelType>, projection?: ProjectionType<ModelType> | null | undefined): Query<IfAny<ModelType, any, Document<...> & Require_id<...>>[], IfAny<...>, {}, ModelType, "find">', gave the following error.
    Argument of type '{ _id: string | Types.ObjectId; }' is not assignable to parameter of type 'FilterQuery<ModelType>'.
      Type '{ _id: string | Types.ObjectId; }' is not assignable to type '{ [P in keyof ModelType]?: Condition<ModelType[P]> | undefined; }'.
  Overload 3 of 5, '(filter: FilterQuery<ModelType>): Query<IfAny<ModelType, any, Document<unknown, {}, ModelType> & Require_id<ModelType>>[], IfAny<...>, {}, ModelType, "find">', gave the following error.
    Argument of type '{ _id: string | Types.ObjectId; }' is not assignable to parameter of type 'FilterQuery<ModelType>'.
      Type '{ _id: string | Types.ObjectId; }' is not assignable to type '{ [P in keyof ModelType]?: Condition<ModelType[P]> | undefined; }'.ts(2769)
```

### Steps to Reproduce

```typescript
import { Model, Types } from "mongoose";

function findById<ModelType extends {_id: Types.ObjectId | string}>(model: Model<ModelType>, _id: Types.ObjectId | string){
    return model.find({_id: _id})
}
```

### Expected Behavior

No Error

**Comment by david-loe** [comment]
Error comes from v8.2.3.
v8.2.2 doesn't had this issue.

**Comment by david-loe** [comment]
related to #14462

**Comment by vkarpov15** [comment]
Looks like OP's script fails to compile with TypeScript 5.4.3:

```
$ ./node_modules/.bin/tsc --strict gh-14459.ts 
gh-14459.ts:4:23 - error TS2769: No overload matches this call.
  Overload 1 of 5, '(filter: FilterQuery<ModelType>, projection?: ProjectionType<ModelType> | null | undefined, options?: QueryOptions<ModelType> | null | undefined): Query<...>', gave the following error.
    Argument of type '{ _id: string | Types.ObjectId; }' is not assignable to parameter of type 'FilterQuery<ModelType>'.
```

I think this is just a limitation of TypeScript, because `{ _id: never }` does satisfy `extends {_id: Types.ObjectId | string}`. For example, the following doesn't cause any errors with using `{ _id: never }`:

```
import { Model, Types, model, Schema } from "mongoose";

function findById<ModelType extends {_id: Types.ObjectId | string}>(model: Model<ModelType>, _id: Types.ObjectId | string){
    return model.find({_id: _id})
}

type ModelType = { _id: never };
const TestModel = model<ModelType>('test', new Schema());

findById<ModelType>(TestModel, 'foo');
```

We will take a quick look to see if there's some way we can work around this weird `never` case

**Comment by vkarpov15** [comment]
I took a look but there's nothing we can do other than 1) make `FilterQuery<T> = any`, or 2) require `as FilterQuery` in OP's case as follows:

```ts
import { Model, Types, model, Schema, FilterQuery } from "mongoose";

function findById<ModelType extends {_id: Types.ObjectId | string}>(model: Model<ModelType>, _id: Types.ObjectId | string){
    return model.find({_id: _id} as FilterQuery<ModelType>);
}
```

This is suboptimal, but unfortunately a limitation of TypeScript. From [this SO answer](https://stackoverflow.com/questions/56505560/how-to-fix-ts2322-could-be-instantiated-with-a-different-subtype-of-constraint): "Never assign a concrete type to a generic type parameter, consider it as read-only!". That includes calling a function with arguments that rely on the generic type parameter.

Even if we make `FilterQuery<T> = T`, we get the following error `'{ _id: string | Types.ObjectId; }' is assignable to the constraint of type 'ModelType', but 'ModelType' could be instantiated with a different subtype of constraint '{ _id: string | ObjectId; }'`

Given that `{ _id: never } extends {_id: Types.ObjectId | string}`, the TypeScript limitation makes sense, just quirky language design.
