### ISSUE TITLE
callback.apply is not a function

### ISSUE THREAD

**Issue by NinjaEde** [Automattic/mongoose#4232]

**Comment by ThariqS** [comment]
I get this same error. My old working repo is fine, with mongoose 4.4.16 but when I upgrade to 4.5 it gives me:

```
[piping] error given was: TypeError: callback.apply is not a function
    at Query.<anonymous> (/Users/thariqshihipar/pubpub-master/node_modules/mongoose/lib/model.js:3343:16)
    at /Users/thariqshihipar/pubpub-master/node_modules/kareem/index.js:244:21
    at /Users/thariqshihipar/pubpub-master/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```

**Comment by vkarpov15** [comment]
@ThariqS please provide code samples

**Comment by wxqee** [comment]
I got the same error.

`     Uncaught TypeError: callback.apply is not a function
      at Query.Model.$wrapCallback (node_modules/mongoose/lib/model.js:3352:16)
      at node_modules/mongoose/node_modules/kareem/index.js:244:21
      at node_modules/mongoose/node_modules/kareem/index.js:127:16
`

Versions of my stuffs:

`wxqee:~/workspace (master) $ mongo --version
MongoDB shell version: 3.2.7
wxqee:~/workspace (master) $ node --version
v4.4.5
`

Npm package.json:
`    "koa": "^0.21.0",
    "koa-router": "^5.1.2",
    "koa-static": "^1.4.9",
    "lodash": "^3.9.3",
    "log4js": "^0.6.26",
    "moment": "^2.10.3",
    "mongoose": "^4.0.6",
    "mongoose-deep-populate": "^2.0.0",
`

**Comment by ron-liu** [comment]
We found the issue still exists. why close it?

**Comment by vkarpov15** [comment]
Please provide code samples

**Comment by wxqee** [comment]
Thanks for your reply. As we don't have time to update the version and fix
some unknown issues, so we decide to use the legacy version of mongoose.
Thinking, after some days, we will review this issue.

Thanks finally!

Regards,
Xiaoqiang


On Tue, Jul 5, 2016 at 12:32 AM, Valeri Karpov <notifications@github.com>
wrote:

> Please provide code samples
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Automattic/mongoose/issues/4232#issuecomment-230324252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AASb9cHBchuJo5uQOgWSK0KiZ_pFoC2Zks5qSTWOgaJpZM4I0x7J>
> .
>



-- 
====================
Good Good Study,
Day Day Up!

**Comment by wxqee** [comment]
Just keep Ron in the loop.

On Tue, Jul 5, 2016 at 1:07 PM, 王晓强 <wxq521@gmail.com> wrote:

> Thanks for your reply. As we don't have time to update the version and fix
> some unknown issues, so we decide to use the legacy version of mongoose.
> Thinking, after some days, we will review this issue.
>
> Thanks finally!
>
> Regards,
> Xiaoqiang
>
>
> On Tue, Jul 5, 2016 at 12:32 AM, Valeri Karpov <notifications@github.com>
> wrote:
>
>> Please provide code samples
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Automattic/mongoose/issues/4232#issuecomment-230324252>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AASb9cHBchuJo5uQOgWSK0KiZ_pFoC2Zks5qSTWOgaJpZM4I0x7J>
>> .
>>
>
>
>
> --
> ====================
> Good Good Study,
> Day Day Up!
>



-- 
====================
Good Good Study,
Day Day Up!

**Comment by ron-liu** [comment]
It looks like the version 4.5.0 introduced some breaking changes, caused most of the queries failed, I will provide some test with simple context shortly.

**Comment by Khekets0** [comment]
Just a notice, this was caused by calling an undefined model

**Comment by vkarpov15** [comment]
What do you mean by calling an undefined model?

**Comment by shubsaini09** [comment]
I get the same error. This is my code. 

`SchemaName.statics.updateName = function(ids, name, callback) {
    this.update({_id:{ "$in": ids}},
        {$set:
            {
                name: name
            }
        }, {upsert:false}, {multi:true}, callback);
};`

**Comment by rodneyrick** [comment]
Hi Everyone,
I still have the same problems with "mongoose": "^4.6.3".

Could anyone help me, please?

`events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: callback.apply is not a function
    at /home/rick/workspace/stormy-basin-91444/node_modules/mongoose/lib/model.js:3343:16
    at Query.<anonymous> (/home/rick/workspace/stormy-basin-91444/node_modules/mongoose/lib/model.js:3343:16)
    at /home/rick/workspace/stormy-basin-91444/node_modules/kareem/index.js:259:21
    at /home/rick/workspace/stormy-basin-91444/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by vkarpov15** [comment]
Please provide a code sample

**Comment by rodneyrick** [comment]
Hi,

When my Rest API call a "res.status(200).json(result.objects)" the same problem again
```
Post.save(post, parent_id, function(result){
    if (result.status){
      res.status(200).json(result.objects);
    } else {
      res.status(404).json(result);
    }  
  });
```
`TypeError: callback.apply is not a function
at ./node_modules/mongoose/lib/model.js:3357:16
at Query.<anonymous> (./node_modules/mongoose/lib/model.js:3357:16)
at ./node_modules/kareem/index.js:259:21
at ./node_modules/kareem/index.js:127:16
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by vkarpov15** [comment]
Your syntax is horribly wrong, just do `post.save()`

**Comment by rodneyrick** [comment]
Sorry for syntax... But this Post is a Class of model MVC, is this case a Control, with same name "save" that Model... However, it has another treatment together.

**Comment by shri0405** [comment]
same problems with "mongoose": "^3.6

Code:
 var match = {
                                                    "$match": {
                                                        "userId": paramsParse.userID,
                                                        "status": 'Open',
                                                    }
                                                }
                                                var groupBy = {
                                                    "$group": {
                                                        "_id": {
                                                            unit: "$unit",
                                                            clientName: "$clientName",
                                                            adCategory: "$adCategory",
                                                            adSubCategory: "$adSubCategory",
                                                            brand: "$brand"
                                                        },
                                                        ticket: { $push: { salesoffice: "$salesoffice", agency: "$agency", orgRegion: "$orgRegion", adType: "$adType", adCaption: "$adCaption", datePublished: "$datePublished" } },
                                                        ticketDetails: {
                                                            $push: {
                                                                adsId: "$adsId",
                                                                id: "$_id",
                                                                page: "$page",
                                                                position: "$position",
                                                                color: "$color",
                                                                adWidth: "$adWidth",
                                                                adHeight: "$adHeight",
                                                                totalAdSpace: "$totalAdSpace"
                                                            }
                                                        }
                                                    }
                                                }

                                                console.log("-----------------condition---------------------", condition);

                                                gConfig.AdsRecords59d8a614983edf2d1fe72d1dSchema.aggregate(match, groupBy).sort({ 'createdOn': 'desc' }).exec(function (errSchema, resGetData) {

**Comment by irfaan008** [comment]
I am using 5.1.2 and having this issue as well

**Comment by lineus** [comment]
@irfaan008 can you create an issue with a reproducible code example that demonstrates the problem you're having? We're happy to help, we just need some details to work with.

**Comment by irfaan008** [comment]
The issue was fixed at code level 
My code which was working with version < 4 was
`Affiliate.aggregate({
                $match: {
                    isActive: 1,
                    _id: Mongoose.Types.ObjectId(b.affiliateId)
                }
            }, {
                $project: { "link": { $concat: ["$affiliateDetail.affiliateLink", "?tag=", b.userId] } }
            },
            function (err, data) {
 // code
 });`


I just wrapped my aggregate code with capital braces `[`
and now new code which works in version >5.0
`Affiliate.aggregate([{
                $match: {
                    isActive: 1,
                    _id: Mongoose.Types.ObjectId(b.affiliateId)
                }
            }, {
                $project: { "link": { $concat: ["$affiliateDetail.affiliateLink", "?tag=", b.userId] } }
            },
            function (err, data) {
 // code
 }]);`
