### ISSUE TITLE
Bug: parentArr.$parent is not a function

### ISSUE THREAD

**Issue by Christilut** [Automattic/mongoose#8519]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

This is happening since I upgraded to 5.8.7:

```
{
kind: embedded, 
reason: 
{
message: parentArr.$parent is not a function, 
name: TypeError, 
stack: 
TypeError: parentArr.$parent is not a function
    at EmbeddedDocument [as constructor] (/var/api/node_modules/mongoose/lib/types/embedded.js:34:43)
    at new EmbeddedDocument (/var/api/node_modules/mongoose/lib/schema/documentarray.js:116:17)
    at DocumentArrayPath.cast (/var/api/node_modules/mongoose/lib/schema/documentarray.js:434:22)
    at DocumentArrayPath.SchemaType.applySetters (/var/api/node_modules/mongoose/lib/schematype.js:975:12)
    at CoreDocumentArray.push (/var/api/node_modules/mongoose/lib/types/core_array.js:664:38)
    at CoreDocumentArray.push (/var/api/node_modules/mongoose/lib/types/documentarray.js:209:28)
    at updateOccasion (/var/server/helpers/import.ts:297:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
}
, 
stringValue: "{ _id: 5e21c7979f535167e350207d,\n  url: \'https://cdn.example.com/123123/9.jpg\',\n  id: \'5e21c7979f535167e350207d\' }", 
value: 
{ _id: 5e21c7979f535167e350207d,
  url: 'https://cdn.example.com/123123/9.jpg',
  id: '5e21c7979f535167e350207d' }
}
```

This occurs when adding an item to an array:
```
          doc.images.push(file)
```

It doesn't always happen, only sometimes. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: `5.8.7`

I was using `5.5.8` before this and this issue never occurred.

**Comment by Christilut** [comment]
I have since downgraded to mongoose `5.8.3` and this problem hasn't happened anymore.

**Comment by vkarpov15** [comment]
This issue report isn't very helpful, please follow the issue template next time. The below script works fine on v5.8.7:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({
    images: [{ url: String }]
  });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ images: [{ url: 'test' }] });

  doc.images.push({ url: 'test2' });

  console.log('Done');
}
```

I'll add an extra check to minimize the risk of this happening for 5.8.10, but please provide a more detailed code sample so we can figure out what's going on. If you can provide the code for `updateOccasion()`, that should help.

**Comment by Christilut** [comment]
This is the `updateOccasion` method with a few unrelated lines removed. I do use Typegoose though, although I think that has no influence here since downgrading resolved the problem.

And this problem only seems to happen occasionally, throughout the day it happened maybe 10 times over thousands of calls.

```
export async function updateOccasion(occ: Occasion, debtor: Debtor, session: mongoose.ClientSession): Promise<DocumentType<Occasion>> {
  const existingOccasion = await Occasion.get(occ, debtor, session)

  for (const key of OCCASION_PROPS_TO_UPDATE) {
    if (key === 'images' || key === 'videos') { // Special case for ExternalFile arrays

      // Find URL's that are in the existing occasion but not in the incoming occasion. These have to be deleted from db and s3.
      const filesToDelete: ExternalFile[] = []
      for (const existingFile of existingOccasion[key] as ExternalFile[]) {
        if (!(occ[key] as ExternalFile[]).some(f => f.url === existingFile.url)) {
          filesToDelete.push(existingFile)
        }
      }

      for (const fileToDelete of filesToDelete) {
        // Remove file from db
        (existingOccasion[key] as ExternalFile[]).splice((existingOccasion[key] as ExternalFile[]).findIndex(f => f.url === fileToDelete.url), 1)

        // Remove from s3
        if (fileToDelete.bucket && fileToDelete.key) {
          await removeFile(fileToDelete.key, fileToDelete.bucket)
        }
      }

      // Add new images that didnt exist yet.
      for (const file of occ[key] as ExternalFile[]) {
        if (!existingOccasion.images.some(f => f.url === file.url)) {
          existingOccasion.images.push(file)
        }
      }
    } else {
      existingOccasion[key] = occ[key]
    }
  }

  if (existingOccasion.isModified()) {
    await existingOccasion.save({
      session
    })
  }

  return existingOccasion
}
```

**Comment by vkarpov15** [comment]
Is there anything different that you can see about the times when this error is thrown? Could you perhaps provide a standalone script I could run that demonstrates this issue?

We made [some fixes with `splice()` in v5.8.7](https://github.com/Automattic/mongoose/blob/master/History.md#587--2020-01-10) with #8482 that may have be related, but the below script runs fine on v5.8.7:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();

  const schema = Schema({
    images: [{ url: String }]
  });
  const Model = mongoose.model('Test', schema);
  await Model.create({ images: [{ url: 'test' }, { url: 'test2' }] });

  const doc = await Model.findOne();

  doc.images.splice(0, 1);
  doc.images.splice(0, 1);

  if (!doc.images.some(f => f.url === file.url)) {
    doc.images.push({ url: 'test2' });
  }

  await doc.save();
  console.log('Done');
}

```

**Comment by Christilut** [comment]
I only saw this happening in production so it's hard to create a repro script. 

I checked the logs for any other info but this was it. Nothing else was happening at the same time either so it's not a concurrency thing.

Just tried to make a script locally that tries to repro but unable to..

I'll try the new mongoose version in production when I'm able to keep an eye on it and report back then.

**Comment by dbellavista** [comment]
I was able to reproduce, I will upload an repro script ASAP

**Comment by dbellavista** [comment]
**NOTE**: with mongoose 5.8.10 I wasn't able to reproduce the issue.

Using mongoose 5.8.7, the issue happens when you push inside an array a mongoose object of the same schema. https://gist.github.com/dbellavista/b63d272dfcb7e748473fd0a2cb1b321c

In the meantime I'm executing some batch test on our production code, to see if there aren't more special cases.

**Comment by vkarpov15** [comment]
@dbellavista I can confirm this was fixed in 5.8.10, probably due to #8509 or maybe #8532.
