### ISSUE TITLE
access model.update in schema method?

### ISSUE THREAD

**Issue by gocoffeecup** [Automattic/mongoose#627]
schema.methods.mySave = function(){
  // dostuffhere
  this.save() 
}
schema.methods.myRemove = function(){
  // dostuffhere
  this.remove() 
}
schema.methods.myUpdate = function(){
  // dostuffhere
  this.update() 
}

first 2 work, but i can't access update within the schema method

**Comment by kerberjg** [comment]
Doesn't seem to work in 5.1.1:

```
TypeError: this.constructor.update is not a function
```

returned by: 

```
UserSchema.methods = {
...
    addPoints: async () => {
        ...
        await this.constructor.update({ _id: this._id }, {
                $inc: incObj
            }, { new: true }).exec();
        ...
    }
}
```

**Comment by vkarpov15** [comment]
@kerberjg there is no 5.1.1 release at the time of this writing. Also, get rid of the arrow function for `addPoints` and it should work because of how arrow functions handle `this`

```javascript
UserSchema.methods = {
...
    addPoints: async function() {
        ...
        await this.constructor.update({ _id: this._id }, {
                $inc: incObj
            }, { new: true }).exec();
        ...
    }
}
```
