### PR TITLE
types: handle compiling with exactOptionalPropertyTypes

### LINKED ISSUE #16273: types: TS2344 error in inferschematype.d.ts and inferrawdoctype.d.ts with exactOptionalPropertyTypes: true and skipLibCheck: false
## Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

## Mongoose version

8.22.1

## Node.js version

22.22.2

## MongoDB server version

N/A (type-checking only, no runtime required)

## TypeScript version

6.0.3 (with `@typescript/native-preview` / tsgo)

## Description

When `skipLibCheck: false` and `exactOptionalPropertyTypes: true` are set in `tsconfig.json`, TypeScript reports `TS2344` errors **inside mongoose's own published `.d.ts` files** — not in user code. The errors occur regardless of what the user's schema looks like; even a minimal schema definition triggers them.

**Root cause:** In two places, mongoose passes `{ enum: Options['enum'] }` as a type argument constrained to `SchemaTypeOptions<Item, any, any>`. Because `enum?` is an optional property on `SchemaTypeOptions`, `Options['enum']` resolves to `T | undefined`. With `exactOptionalPropertyTypes: true`, TypeScript strictly distinguishes a required property holding `undefined` from an absent optional property — so `{ enum: T | undefined }` (required, can be `undefined`) fails to satisfy `{ enum?: T }` (optional, no `undefined`).

**Regression bisect:**

| Version | Errors |
|---------|--------|
| 8.18.0  | ✅ 0   |
| 8.18.1  | ❌ 1 — `inferschematype.d.ts` (introduced by #15605) |
| 8.19.0  | ❌ 2 — `inferrawdoctype.d.ts` additionally (introduced by #15588) |
| 8.22.1  | ❌ 2   |

## Steps to Reproduce

**Reproduction repo:** https://github.com/nnoce14/mongoose-type-error-sample-repo

```bash
git clone https://github.com/nnoce14/mongoose-type-error-sample-repo
cd mongoose-type-error-sample-repo
npm install
npm run typecheck
```

**`tsconfig.json` (relevant options):**
```json
{
  "compilerOptions": {
    "strict": true,
    "exactOptionalPropertyTypes": true,
    "skipLibCheck": false,
    "module": "NodeNext",
    "moduleResolution": "nodenext"
  }
}
```

**`src/index.ts`:**
```ts
import mongoose from "mongoose";

interface IUser {
  name: string;
  email: string;
  createdAt: Date;
}

const userSchema = new mongoose.Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  createdAt: { type: Date, default: Date.now },
});

export const User = mongoose.model<IUser>("User", userSchema);
```

**Errors produced:**
```
node_modules/mongoose/types/inferrawdoctype.d.ts:75:84 - error TS2344:
  Type '{ enum: Options["enum"]; }' does not satisfy the constraint 'SchemaTypeOptions<Item, any, any>'.
    Types of property 'enum' are incompatible.
      Type 'Options["enum"]' is not assignable to type '(string | number | null)[] | ...'.
        Type 'undefined' is not assignable to type '(string | number | null)[] | ...'.

node_modules/mongoose/types/inferschematype.d.ts:285:81 - error TS2344:
  Type '{ enum: Options["enum"]; }' does not satisfy the constraint 'SchemaTypeOptions<Item, any, any>'.
    Types of property 'enum' are incompatible.
      Type 'Options["enum"]' is not assignable to type '(string | number | null)[] | ...'.
        Type 'undefined' is not assignable to type '(string | number | null)[] | ...'.
```

## Expected Behavior

Type-checking passes with no errors. Mongoose's own type definitions should be internally consistent when `exactOptionalPropertyTypes: true` is used.

**Suggested fix** — change the two offending lines from a required property to an optional one:

```diff
// inferrawdoctype.d.ts:75
- ResolveRawPathType<Item, { enum: Options['enum'] }, TypeKey>[]
+ ResolveRawPathType<Item, { enum?: Exclude<Options['enum'], undefined> }, TypeKey>[]

// inferschematype.d.ts:285
- ResolvePathType<Item, { enum: Options['enum'] }, TypeKey>[]
+ ResolvePathType<Item, { enum?: Exclude<Options['enum'], undefined> }, TypeKey>[]
```

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #16273

**Summary**

Fix compiling with TypeScript's `exactOptionalPropertyTypes` flag. I also added a separate test folder with a separate `tsconfig.json` for testing compiling with that flag set.

**Examples**

### CODE REVIEW

**Comment by mrazauskas** [comment]
It is more involving, but perhaps it is worth setting `"exactOptionalPropertyTypes": true` directly in `test/types/tsconfig.json` for all type tests? Code that compiles when "exactOptionalPropertyTypes" is enabled, would also compile when it is disabled.

I can do this next week (after my vacation).

**Comment by vkarpov15** [comment]
That seems reasonable. I'll merge this for now to unblock people.
