### ISSUE TITLE
required property in schema when passed to InferSchemaTypes is optional

### ISSUE THREAD

**Issue by naquiuddin** [Automattic/mongoose#13514]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.11.2

### Node.js version

18.16.0

### MongoDB server version

6.0

### Typescript version (if applicable)

4.9.5

### Description

The InferSchemaTypes is wrongly creating type for a field that has custom message validation.

### Steps to Reproduce

For example when running InferSchemaType on a schema that has a field with custom error message validation like this:
```ts
    email: {
         type: string,
         required: [true, "email is required"]
    }
```
It returns type as 
`email: string | undefined`

### Expected Behavior

Ideally this has to be.
`email: string`
in type definition

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script compiles fine on TypeScript 4.9.5:

```ts
import { Schema, model } from 'mongoose';

const schema = new Schema({
  email: {
    type: String,
    required: [true, "email is required"]
  } 
});
const Test = model('Test', schema);

const doc = new Test({ email: 'bar' });
const str: string = doc.email;
```

Output:

```
$ ./node_modules/.bin/tsc --strict gh-13514.ts 

$
```

Can you please confirm whether the above script fails to compile for you, and, if so, what's your tsconfig.json?

**Comment by davidbayo10** [comment]
Same problem when hovering over the schema field. It works correctly when application is built with TSC.

![image](https://github.com/Automattic/mongoose/assets/6841248/8ba65915-5201-4981-9f44-a9f030276491)

**Comment by vkarpov15** [comment]
@davidbayo10 what editor are you using and can you please provide a more complete code sample?

**Comment by YazanDuelLinks** [comment]
@vkarpov15 This is a sample running on mongoose v7.3.2, TS 5.1.6 under VS Code with a fresh TS project that provides a default config file.
Using an array results into optional property (copying your own code)
```ts
import { Schema, model } from 'mongoose';

const schema = new Schema({
  email: {
    type: String,
    required: [true, "email is required"]
  } 
});
const Test = model('Test', schema);

const doc = new Test({ email: 'bar' });
const str: string = doc.email;
```
Output
```
index.ts:12:7 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

12 const str: string = doc.email;
         ~~~
```
While this compiles with no issue if a boolean is used directly
```ts
import { Schema, model } from 'mongoose';

const schema = new Schema({
  email: {
    type: String,
    required: true
  } 
});
const Test = model('Test', schema);

const doc = new Test({ email: 'bar' });
const str: string = doc.email;
```
I'm using this in a big project so the only way around it was to assign a default value

**Comment by lobotomoe** [comment]
Can confirm that. After upgrading TS from 5.0.4 to 5.1.6 having same issue. `required: true` doesn't infer type correctly anymore. Field is optional now.

**Comment by davidbayo10** [comment]
> @davidbayo10 what editor are you using and can you please provide a more complete code sample?

I apologize for not mentioning it earlier, but I am using VSCode

**Comment by IslandRhythms** [comment]
The following script compiles no issue for me. Tested on 6.11.2 and 7.3.4 and Typescript 5.1.6

```typescript
import { Schema, model } from 'mongoose';

const schema = new Schema({
  email: {
    type: String,
    required: [true, "email is required"]
  } 
});
const Test = model('Test', schema);

const doc = new Test({ email: 'bar' });
const str: string = doc.email;
```

**Comment by YazanDuelLinks** [comment]
> The following script compiles no issue for me. Tested on 6.11.2 and 7.3.4 and Typescript 5.1.6
> 
> ```ts
> import { Schema, model } from 'mongoose';
> 
> const schema = new Schema({
>   email: {
>     type: String,
>     required: [true, "email is required"]
>   } 
> });
> const Test = model('Test', schema);
> 
> const doc = new Test({ email: 'bar' });
> const str: string = doc.email;
> ```

Not sure how are you compiling this, but tested on v7.3.4, TS 5.1.6 and VSCode again
Using tsc (make sure you compile as a project not a file because tsc ignores tsconfig's strict rule otherwise)
```ts
index.ts:12:7 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

12 const str: string = doc.email;
         ~~~
```
Using ts-node
```ts
  return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:12:7 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

12 const str: string = doc.email;
```
Both output the same error
Further more VScode shows an error red line under the variable trigged by TS in the code editor.

**Comment by IslandRhythms** [comment]
I can't confirm your bug but I am getting something similar
![image](https://github.com/Automattic/mongoose/assets/39510674/1fd3c026-1b74-4b6f-ad72-8baa3b5390eb)

**Comment by vkarpov15** [comment]
Looks like this was a backwards breaking change introduced in TypeScript 5.1. The easiest workaround is to downgrade to TypeScript 5.0.x. We're working on a fix.

**Comment by vkarpov15** [comment]
Another workaround is to add an explicit type cast as follows:

```ts
import { Schema, model } from 'mongoose';

const schema = new Schema({
  email: {
    type: String,
    required: [true, "email is required"] as [true, string] // <-- add this `as` to appease TypeScript 5.1
  } 
});
const Test = model('Test', schema);

const doc = new Test({ email: 'bar' });
const str: string = doc.email;
```

I haven't been able to repro this issue in TypeScript playground, but the issue is that TypeScript is no longer recognizing `{ type: String, required: [true, 'email is required'] }` as `extends { required: [true, string | undefined] }`.  TypeScript is no longer recognizing `true` as a const or `[true, 'email is required']` as a length 2 array, because the following also don't work anymore:

 1. `extends { required: [any, any] }`
 2. `extends { required: (true | string)[]`

But the following _do_ compile correctly

1. `extends { required: (boolean | string)[] }`
2. `extends { required: any[] }`

Unfortunately, there's no good way for Mongoose to fix this issue, it's likely a TypeScript bug. However, there are a few workarounds as follows:

```ts
const schema = new Schema({
  email: {
    type: String,
    required: [true, "email is required"] as [true, string] // <-- add this `as` to appease TypeScript 5.1
  } 
});
```

```ts
const schema = new Schema({
  email: {
    type: String,
    required: true
  }
});
schema.path('email').required(true, 'Email is required');
```

```ts
const schema = new Schema({
  email: {
    type: String,
    required: {
      isRequired: true as true, // <-- add `as` to appease TypeScript 5.1
      message: 'email is required'
    }
  }
});
```

**Comment by vkarpov15** [comment]
Try `false as false` or `as const` after your schema definition?
