### ISSUE TITLE
Sub-document validation doesn't work with runValidators

### ISSUE THREAD

**Issue by valterkraemer** [Automattic/mongoose#4420]
runValidators seems to not work with subdocuments

```
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/test');

var FileSchema = new Schema({
  name: String
});

var CompanySchema = new Schema({
  name: String,
  file: FileSchema
});

var Company = mongoose.model('Company', CompanySchema);

Company.create({
  name: 'Mapple'
})
.then(function(company) {
  return Company.update({
    _id: company._id
  }, {
    file: {
      name: 'new-name'
    }
  }, {
    runValidators: true
  });
});
```

Stack trace

```
Unhandled rejection TypeError: value.validate is not a function
    at .../node_modules/mongoose/lib/schema/embedded.js:151:11
    at SchemaType.doValidate (.../node_modules/mongoose/lib/schematype.js:694:12)
    at SchemaType.Embedded.doValidate (.../node_modules/mongoose/lib/schema/embedded.js:144:35)
    at .../node_modules/mongoose/lib/services/updateValidators.js:71:20
    at .../node_modules/mongoose/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (.../node_modules/mongoose/node_modules/async/lib/async.js:233:13)
    at _parallel (.../node_modules/mongoose/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (.../node_modules/mongoose/node_modules/async/lib/async.js:731:9)
    at .../node_modules/mongoose/lib/services/updateValidators.js:90:11
    at Query._execUpdate (.../node_modules/mongoose/lib/query.js:1984:7)
    at .../node_modules/mongoose/node_modules/kareem/index.js:239:8
    at .../node_modules/mongoose/node_modules/kareem/index.js:18:7
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

mongoose version: 4.5.9
mongodb version: 3.2.4

**Comment by joaoreynolds** [comment]
I had the same issues with mongoose v4.6.0

**Comment by vkarpov15** [comment]
@joaoreynolds please provide code samples. We have a test for this case and it's passing.

**Comment by joaoreynolds** [comment]
I'm glad you requested a code sample, I was attempting to simplify my code to make it shareable here, and I noticed I was doing this in my schema (making a nested object a schema, even if it is not itself an array element - so it shouldn't be a subdocument):
```
reviews: [
      new mongoose.Schema(
        {
          department: new mongoose.Schema({
            _id: false,
            deptId: { type: mongoose.Schema.Types.ObjectId, ref: 'Department'},
            name: String,
            abbr: String
          }),
          user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        }
      )
],
```
Which was causing this error when I did a `findByIdAndUpdate`: 
```
error: value.validate is not a function TypeError: value.validate is not a function
    at /Users/.../node_modules/mongoose/lib/schema/embedded.js:155:11
    at SchemaType.doValidate (/Users/.../node_modules/mongoose/lib/schematype.js:694:12)
```
Which made be believe validation was failing on subdocuments (and this error only started appearing when I updated to v4.6.0 with no changes to my schema, which is why I blamed 4.6)

So I fixed my Schema to be:
```
reviews: [
      new mongoose.Schema(
        {
          department: {
            deptId: { type: mongoose.Schema.Types.ObjectId, ref: 'Department'},
            name: String,
            abbr: String
          },
          user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        }
      )
],
```
Which is more accurate. Hopefully at least this helps anyone else seeing the same error. Thanks @vkarpov15
