### ISSUE TITLE
ERROR: mongoose.connect is not a function

### ISSUE THREAD

**Issue by chauanphu** [Automattic/mongoose#11803]
Hi, I need to report a bug

### The Problem
Even though it has connected to the database server, and _moongose_ object has been created, it still reports the problem: 

![image](https://user-images.githubusercontent.com/77331326/168305460-c96f4208-9d3e-4735-8f67-27abecd865e5.png)

### This how my code looks like
```
const mongoose = require("mongoose");
const key = require("dotenv").config();

const uri = `mongodb+srv://${key.parsed.MONGODB_ACCOUNT}:${key.parsed.MONGODB_PASSWORD}@infinity-lotus.r8wbj.mongodb.net/${key.parsed.MONGODB_DB}?retryWrites=true&w=majority`;
console.log(mongoose);
mongoose.connect(uri).then(() => {
  console.log("Connected");
});
export default mongoose;
```

### Platform
- Window 10
- vue: "^3.0.0",
- vuex: "^4.0.0-0"
- electron: "^13.0.0",
- mongoose: "^6.2.2", ( both 6.2.2 and 6.2.3 generates the error )
- npm: v16.15.0

### Additional Info
I don't know if this is helpful but I run this code as a module in store/index.js. 
Before that I tried to create connection by using _mongodb_ and it has no problem.

**Comment by awesomelike** [comment]
You cannot use that method in the browser, see: https://mongoosejs.com/docs/browser.html

**Comment by 8BitJonny** [comment]
Is there any documentation, why mongoose doesn't want to support connecting to the db from a browser?

I know it's generally considered a bad practice, but I'm looking into how the library support is for building a database GUI in a JS / NODE cross platform environment. And in this specific use case the end-user needs connect from the App / Frontend, since he is the one to provide the db credentials.
I think I found one PR here, where you dropped create-react-app support because it's such a niche use case, but any further pointers on this would be greatly appreciated

**Comment by wsw954** [comment]
I had a similar error:mongoose__WEBPACK_IMPORTED_MODULE_0___default(...).connect is not a function
After an exhausting review, the only thing that worked for me is when I switched to an older version of mongoose.  I went from a version 7 to a version "mongoose": "^6.12.1".  And that worked
