### ISSUE TITLE
Cannot read property 'caster' of undefined with Array.push

### ISSUE THREAD

**Issue by FrankMerema** [Automattic/mongoose#6471]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Current behaviour (mongoose 5.0.16) is supporting Array.push. In the next versions of mongoose 5.0.17 until 5.1.1 it's throwing the `Cannot read property 'caster' of undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const s = new Schema({
    created: {type: Date, default: Date.now()},
    name: String,
    someArray: {type: Array, default: []}
});

const m = mongoose.model('some', s);
```
```
function updateModel(someId) {
    m.find({_id: "someId"})
        .then(items => {
            items[0].someArray.push({
                executed: new Date(),
                executedBy: 'System'
            });

        // This will never be called, it will crash on the push in v5.1.x
        return m.save();
    });
}
```

**What is the expected behavior?**
It will push the object into the array and save it to Mongo. It did work in v5.0.16.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v9.11.1
NPM: v5.6.0
Mongoose: v5.0.16
MongoDB: v3.6.3

**StackTrace**
```
TypeError: Cannot read property 'caster' of undefined
at Array._cast (/node_modules/mongoose/lib/types/array.js:123:25)
at Array._mapCast (/node_modules/mongoose/lib/types/array.js:301:17)
at Arguments.map (<anonymous>)
at Array.push (/node_modules/mongoose/lib/types/array.js:315:25)
```

**Comment by lineus** [comment]
@FrankMerema I tried to create a complete and reproducible script from your comment. `m` is declared as the model, so calling `m.save()` was changed to `item[0].save()`:

### 6471.js on mongoose v5.1.1
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const s = new Schema({
  created: { type: Date, default: Date.now() },
  name: String,
  someArray: { type: Array, default: [] }
});

const m = mongoose.model('some', s);

const test = new m({
  name: 'Volker'
});

function updateModel(someId) {
  return m.find({ _id: someId })
    .then(items => {
      items[0].someArray.push({
        executed: new Date(),
        executedBy: 'System'
      });

      return items[0].save(); // `m.save()` is not a function
    });
}

async function run() {
  await conn.dropDatabase();
  await test.save();
  await updateModel(test._id);
  let found = await m.findOne();
  console.log(found);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6471.js
{ created: 2018-05-15T10:22:21.291Z,
  someArray:
   [ { executed: 2018-05-15T10:22:21.723Z, executedBy: 'System' } ],
  _id: 5afab4dd0107ad7ab7c678d7,
  name: 'Volker',
  __v: 1 }
issues:
```

**Can you create a complete repro script ( or modify mine ) to demonstrate the issue you are experiencing?**

**Comment by FrankMerema** [comment]
I have found the problem! I was using a library for generic support in Typescript and the dependency was outdated to 5.0.16. Apparently the versions need to be the same in order to work. Thanks for investigating it! Will close the issue as it is resolved.

**Comment by mazyvan** [comment]
I'm having this issue. I'm ussing `5.11.19`
