### ISSUE TITLE
TypeError: scope.populated is not a function

### ISSUE THREAD

**Issue by janantala** [Automattic/mongoose#9986]
Hello there,

I am getting this error after updating to mongoose v5.11.18 from v5.11.9
Edit v5.11.15 was fine, the problem is from v5.11.16

```
TypeError: scope.populated is not a function
  at SchemaArray.applyGetters (/Users/janantala/github/directory/node_modules/mongoose/lib/schema/array.js:264:30)
    at schema.eachPath (/Users/janantala/github/directory/node_modules/mongoose-lean-getters/index.js:76:32)
    at Schema.eachPath (/Users/janantala/github/directory/node_modules/mongoose/lib/schema.js:1038:5)
    at applyGettersToDoc (/Users/janantala/github/directory/node_modules/mongoose-lean-getters/index.js:75:10)
```

It is a query function using lean getters:

```
mongoose.model('Device').find(req.query || {}).lean({defaults: true, getters: true, virtuals: true}).exec(function(err, devices) {
    console.log(err);
    if (err) {
      return next(err);
    }
    res.json(devices);
  });
```

It looks like caused by this commit: https://github.com/Automattic/mongoose/commit/b3013744121cab4ef1c4e25a48887dacb4224107 @vkarpov15 

Can you help?

Jan Antala

**Comment by janantala** [comment]
Referenced in: https://github.com/Automattic/mongoose/issues/9889

**Comment by janantala** [comment]
Hello, do you have any update issue? Or do you need more details?

**Comment by vkarpov15** [comment]
Hi @janantala we'll need a more complete repro script, including schemas. Nothing looks obviously wrong from the code you pasted, but hard to tell without schema definitions.

**Comment by janantala** [comment]
Hi @vkarpov15 there is a repro script: https://github.com/janantala/mongoose-9986

you need a local mongo cluster running `run-rs -v 4.0.2` and then you can run tests by `npx gulp`

As you can see tests are failing on ` "mongoose": "5.11.19"` when I downdgrade it to ` "mongoose": "5.11.15"` it is running fine.

When I remove this nested `monitoring` object https://github.com/janantala/mongoose-9986/blob/main/app/models/device.server.model.js#L67-L84 from schema tests are also passing.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/fa3d832a1c4f7102450ba119ee375ee59ff365c2
