### ISSUE TITLE
Clean project fails to build using typescript and 6.0.8

### ISSUE THREAD

**Issue by TaylorBenner** [Automattic/mongoose#10795]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Fresh project using mongoose produces TS error.  

Steps:    
```
1. mkdir new-project && cd new-project
2. npm init -y
3. tsc --init
4. npm i --save-dev typescript @types/node
5. npm i mongoose
6. mkdir src && echo "import mongoose from 'mongoose'" >> src/index.ts
7. tsc -p .
```

TSConfig:    
```
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

Output:     
```
node_modules/mongodb/mongodb.ts34.d.ts:4844:89 - error TS2344: Type 'Flatten<TSchema[key]>' does not satisfy the constraint '{ _id?: any; }'.
  Type 'unknown' is not assignable to type '{ _id?: any; }'.
    Type 'Flatten<TSchema[{ [key in keyof TSchema]: NonNullable<TSchema[key]> extends readonly any[] | undefined ? key : never; }[keyof TSchema]]>' is not assignable to type '{ _id?: any; }'.
      Type 'unknown' is not assignable to type '{ _id?: any; }'.
        Type 'Flatten<TSchema[NonNullable<TSchema[keyof TSchema]> extends readonly any[] | undefined ? keyof TSchema : never]>' is not assignable to type '{ _id?: any; }'.
          Type 'unknown' is not assignable to type '{ _id?: any; }'.
            Type 'Flatten<TSchema[keyof TSchema]>' is not assignable to type '{ _id?: any; }'.
              Type 'unknown' is not assignable to type '{ _id?: any; }'.
                Type 'Flatten<TSchema[string | number | symbol]>' is not assignable to type '{ _id?: any; }'.
                  Type 'unknown' is not assignable to type '{ _id?: any; }'.
                    Type 'Flatten<TSchema[string]> | Flatten<TSchema[number]> | Flatten<TSchema[symbol]>' is not assignable to type '{ _id?: any; }'.
                      Type 'Flatten<TSchema[string]>' is not assignable to type '{ _id?: any; }'.
                        Type 'unknown' is not assignable to type '{ _id?: any; }'.

4844     readonly [key in KeysOfAType<TSchema, ReadonlyArray<any> | undefined>]?: OptionalId<Flatten<TSchema[key]>> | AddToSetOperators<Array<OptionalId<Flatten<TSchema[key]>>>>;
                                                                                             ~~~~~~~~~~~~~~~~~~~~~

node_modules/mongodb/mongodb.ts34.d.ts:4844:149 - error TS2344: Type 'Flatten<TSchema[key]>' does not satisfy the constraint '{ _id?: any; }'.

4844     readonly [key in KeysOfAType<TSchema, ReadonlyArray<any> | undefined>]?: OptionalId<Flatten<TSchema[key]>> | AddToSetOperators<Array<OptionalId<Flatten<TSchema[key]>>>>;
                                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

**What is the expected behavior?**
No errors are produced.

**What are the versions of Node.js, Mongoose and MongoDB you are using?**
node: v16.4.2
mongoose: 6.0.8
mongo:5.0.3

**Comment by sean-daley** [comment]
Might be good to report this to the mongodb project since the errors are there and you can reproduce the issue by doing your steps as well but replacing mongoose with mongodb (so completely take mongoose out of the equation).

What typescript version are you using? I was not able to reproduce this with typescript 4.1 and newer but could reproduce it with typescript 4.0.2. The mongodb folks do have a different version of their types which they use once you are using 4.0.2 or older (the mongodb.ts34.d.ts types). Since it looks like, from your error, those are the types you are getting, I'm assuming you are using something 4.0.2 or older?

**Comment by vkarpov15** [comment]
What version of TypeScript are you using @TaylorBenner ?

**Comment by TaylorBenner** [comment]
Thought I was on the latest version, but my TS was pretty old.  Version 3.8.3.  I updated to 4.4.3 and the issue is no longer present.
