### ISSUE TITLE
Incompatible types with array of ObjectId after upgrading to 6.0.1

### ISSUE THREAD

**Issue by pqvst** [Automattic/mongoose#10623]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Creating a schema with an array of ObjectId and defining a corresponding TypeScript interface causes a compiler error, stating that the types are incompatible.

A single ObjectId (no array) works fine though. Arrays of other types also work fine. It just seems to be array of ObjectId which is problematic.

![image](https://user-images.githubusercontent.com/4990657/131044054-a5657ebf-4823-47e2-8d81-6348c146fc43.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
import { Schema, model, ObjectId, Document } from 'mongoose';

interface Foo extends Document<ObjectId> {
  arrayOfObjectId: ObjectId[];
}

const fooSchema = new Schema<Foo>({
  arrayOfObjectId: { type: [Schema.Types.ObjectId], required: true },
});
```

tsconfig.json

```
{
  "compilerOptions": {
    "outDir": "./build",
    "allowJs": true,
    "target": "ES2018",
    "module": "CommonJS",
    "sourceMap": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": [
      "types", // must be first!
      "node_modules/@types"
    ]
  }
}
```

**What is the expected behavior?**
Before upgrading to mongoose v6 I was able to create a schema with an array of ObjectId and use a corresponding TypeScript interface. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v16.3.0
mongoose: 6.0.1
