### ISSUE TITLE
toObject() with flattenObjectIds set to true does not expect to return an object with _id : string

### ISSUE THREAD

**Issue by Kowah** [Automattic/mongoose#16064]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

9.2.0

### Node.js version

24.7.0

### MongoDB server version

8.0.13

### Typescript version (if applicable)

5.8.3

### Description

A Typescript error occurs when calling `toObject()` with `flattenObjectIds` set to true and expecting an object with  `_id` of type string. Since mongoose@9.2.0, it's returning an object with `_id` of type ObjectId.

```Types of property '_id' are incompatible. Type 'ObjectId' is not assignable to type 'string'.```

### Steps to Reproduce

Use `toObject()` with any mongoose version between 9.2.0 & 9.2.3

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script compiles fine with Mongoose 9.2.3 and TypeScript 5.8.3. Can you modify the following script to demonstrate the issue you're seeing?

```ts
import mongoose from 'mongoose';

const schema = new mongoose.Schema({ name: String });
const TestModel = mongoose.model('Test', schema);

const doc = new TestModel();
const obj = doc.toObject({ flattenObjectIds: true });
const id: string = obj._id;

```

**Comment by Kowah** [comment]
@vkarpov15 Can you share your tsconfig ? Because i can't even compile your code, got this issue on `doc.toObject({ flattenObjectIds: true })` :

`Property 'toObject' does not exist on type 'Schema<any, Model<any, any, any, any, any, any, any>, {}, {}, {}, {}, DefaultSchemaOptions, { name?: string | null | undefined; }, Document<unknown, {}, { name?: string | ... 1 more ... | undefined; }, { ...; }, DefaultSchemaOptions> & Omit<...> & { ...; }, { ...; } | { ...; }, { ...; } & ... 1 more ... & { ...; }>'.ts(2339)`

**Comment by vkarpov15** [comment]
No tsconfig, I'm just running `tsc --strict gh-16064.ts`. What does your tsconfig look like?

**Comment by Kowah** [comment]
Ok, I tested it first on my project and an old plugin was breaking mongoose types.
So, here is an upgraded version of your code which totally corresponds to my usecase and i find the same error 

(now using 9.3.0)

```
import mongoose from 'mongoose';

interface TestType {
    _id: string
    name: string

}

const schema = new mongoose.Schema({ name: String });
const TestModel = mongoose.model('Test', schema);

const doc = new TestModel();
const obj : TestType = doc.toObject({ flattenObjectIds: true });
const id: string = obj._id;
```

**Comment by vkarpov15** [comment]
Your script fails to compile due to `name` being incompatible not due to an issue with flattenObjectIds, the following compiles fine because it has the correct type for `name`

```ts
import mongoose from 'mongoose';

interface TestType {
    _id: string
    name?: string | null // Since `name` is not required, it can be null or undefined
}

const schema = new mongoose.Schema({ name: String });
const TestModel = mongoose.model('Test', schema);

const doc = new TestModel();
const obj : TestType = doc.toObject({ flattenObjectIds: true }); // Works
const id: string = obj._id; // Works
```

**Comment by Kowah** [comment]
What am I expecting in Model and Schema T ? On my project we are giving interfaces extending mongoose.Document, shall I use TestType or ITestTypeDocument in my next example ?

I remember we used Document extensions because we have subdocuments ids in our documents.

```csharp
import mongoose from 'mongoose'

interface TestType {
  _id: string
  name?: string | null
}

interface ITestTypeDocument extends mongoose.Document {
  _id: mongoose.Types.ObjectId
  name?: string | null
}

const schema = new mongoose.Schema<ITestTypeDocument>() //Shall it be Schema<TestType> ?
const TestModel = mongoose.model<ITestTypeDocument>('Test', schema) //Shall it be Schema<TestType> ?

const test = await TestModel.findOne()

if (test) {
  const obj: TestType = test.toObject({ flattenObjectIds: true }) //Not working
  const id: string = obj._id
}

```

Depending of your answer I'll work on giving you an example with subdocuments ids.
What I'm sure is I did not change anything on my code between 9.1.X versions and 9.2.X+ versions.

Thank you for your time 👍

**Comment by vkarpov15** [comment]
You should get rid of the `extends mongoose.Document` part, [Mongoose dropped support for doctypes that `extends Document` in Mongoose 7.0.0](https://mongoosejs.com/docs/migrating_to_7.html#removed-leandocument-and-support-for-extends-document). The following compiles correctly.

```ts
import mongoose from 'mongoose'

interface TestType {
  _id: string
  name?: string | null
}

interface ITestTypeDocument {
  _id: mongoose.Types.ObjectId
  name?: string | null
}

async function main() {
const schema = new mongoose.Schema<ITestTypeDocument>() //Shall it be Schema<TestType> ?
const TestModel = mongoose.model<ITestTypeDocument>('Test', schema) //Shall it be Schema<TestType> ?

const test = await TestModel.findOne()

if (test) {
  const obj: TestType = test.toObject({ flattenObjectIds: true }) //Not working
  const id: string = obj._id
}
}
```
