### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by HamoBoker** [Automattic/mongoose#11787]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
i'm generating interfaces using [mongoose-tsgen](https://github.com/francescov1/mongoose-tsgen#example) and everything works fine in mongoose <=6.3.1, but on v6.3.2 or v6.3.3 i get this ts error `TS2589: Type instantiation is excessively deep and possibly infinite`, also im not using `@types/mongoose`

**If the current behavior is a bug, please provide the steps to reproduce.**
`await SomeModel.findById(id)`
you can test example code in [mongoose-tsgen](https://github.com/francescov1/mongoose-tsgen#example)

**tsconfig.json**
```
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "ts-node": {
    "transpileOnly": true,
    "files": true
  },
  "compilerOptions": {
    "moduleResolution": "Node",
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "removeComments": true,
    "noUnusedLocals": false,
    "newLine": "lf",
    "noImplicitAny": true,
    "pretty": true,
    "noEmitOnError": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules/**"]
}
```

**What is the expected behavior?**
ts build without errors

**Thank you so much for you great work**

**Comment by IslandRhythms** [comment]
It must be something with your setup, I can't reproduce it on my end.

**Comment by Uzlopak** [comment]
Does it also happen when transpiling with tsc? Does it only happen in vscode? Which typescript version do you use in vscode? Which in your project? What happens when you update typescript? What when you update vscode?

**Comment by HamoBoker** [comment]
Yes, i'm using webstorm but i tested it on vscode also i get same error, on `mongoose@6.3.1` everything works fine but its not working on 6.3.2 & 6.3.3

```
node: v16.15.0
typescript: v4.6.4 (latest) in project and IDE
device: macOS 12.3.1 (M1)
```

when running `tsc` command i get this
```console
src/models/User.ts:4:52 - error TS2589: Type instantiation is excessively deep and possibly infinite.

4 const UserSchema: UserSchema = new mongoose.Schema({
                                                     ~
5   name: String
  ~~~~~~~~~~~~~~
6 });
  ~
```

heres the new project that contains the code snippet above and it produces the problem 
[node-demo.zip](https://github.com/Automattic/mongoose/files/8673728/node-demo.zip)

npm i && npx mtgen

**Comment by mohammad0-0ahmad** [comment]
Using mongoose v6.3.1 the error will disappear for now.
I guess LeanDocument type "not sure yet" make this breaking change.
I think @taxilian can help with that better here.

**Comment by IslandRhythms** [comment]
I downloaded your zip and ran it and still can't reproduce, it's something with your setup.

**Comment by mohammad0-0ahmad** [comment]
> I downloaded your zip and ran it and still can't reproduce, it's something with your setup.

Hello @IslandRhythms !
I've got it on my setup, can you test it again after restarting VSC?
![Untitled](https://user-images.githubusercontent.com/50488054/168316722-cfcd00df-c7f8-4583-9b59-7640a0c96873.png)

**Comment by IslandRhythms** [comment]
Got it

**Comment by mohammad0-0ahmad** [comment]
Hello @francescov1!
I've noticed that populate FN overloading in auto generated type "mongoose.gen" is what cause this error with the new versions types.
So you might check that to solve this issue.
I don't think we need to fix this breaking change in mongoose. @IslandRhythms

**Comment by francescov1** [comment]
@HamoBoker This incompatibility is turning out to be a bit tougher to uncover than I expected. For now, you can continue using mongoose-tsgen with the `--no-populate-overload` flag to resolve the problem (but won't be able to benefit from population inference). 

@mohammad0-0ahmad Any idea on the expected timeline for your PR https://github.com/Automattic/mongoose/pull/11563. This PR removes the need for mongoose-tsgen, so depending on when it gets merged it may not be worth trying to fix the issue in mongoose-tsgen.

**Comment by mohammad0-0ahmad** [comment]
@francescov1  sorry for that, I don't really know when it will be exactly merged, but @vkarpov15  said it will be shipped with the next minor release "6.4.0"

**Comment by HamoBoker** [comment]
Ok I'll stick with this solution for now

Thank you guys for your great work, I really appreciate it

**Comment by vkarpov15** [comment]
@francescov1 thanks for looking into this and thanks for the lib, mongoose-tsgen is :+1: . You're right that the `populate()` override is what causes the "Type instantiation is excessively deep and possibly infinite" error, however, I haven't been able to figure out a way to avoid that error without removing the `PopulatedDocument` type entirely.

 I really like this `PopulatedDocument` type. Very handy if you're defining your document interfaces using `mongoose.Types.ObjectId | ChildDoc`. `PopulatedDocument` is missing a couple of edge cases. For example, it is perfectly fine to populate fields that aren't of type `ObjectId`, like numbers or strings. We even support populating subdocuments in place.

But, again, this sort of TypeScript bug is very hard to diagnose. We'll keep this open for the future, and consider pulling in the `PopulatedDocument` abstraction into Mongoose's types.

**Comment by francescov1** [comment]
@vkarpov15 Thanks for checking this out, too bad there are not any obvious fixes. 

Im thinking of stopping maintenance on mongoose-tsgen as the new type inference in 6.4.0 should accomplish the same goal, can you confirm that? 

Sounds like the `PopulatedDocument` type may still be useful; I'd be happy to help integrate it into Mongoose if this is the case, let me know! I find it to be quite nice since most of my `populate` return types are automatically inferred, and if they cannot be then we just fallback to `mongoose.Types.ObjectId | ChildDoc`.

**Comment by francescov1** [comment]
@vkarpov15 Can we expect this to be resolved by the Mongoose team, or is this is an issue with mongoose-tsgen? Would like to try getting it resolved soon since its a breaking issue for many users. I havent had any luck fixing it yet, but not sure if I should be focusing on fixing it from my end or from the Mongoose types. Also just finding it hard to track down the root cause since the error is so generic.

**Comment by mohammad0-0ahmad** [comment]
@francescov1 try to override LeanDocument helper type, I think this issue is related to the changes made on that.

**Comment by vkarpov15** [comment]
@francescov1 as far as I can tell, this is an issue with mongoose-tsgen. We've been trying to improve the mongoose-tsgen type output, but haven't been able to fix it.

**Comment by francescov1** [comment]
I just reviewed this again, it seems the issue has been resolved as of Mongoose v6.4.1 (so it only affects Mongoose 6.3.2 - 6.4.0). I think we can close this @HamoBoker @vkarpov15 ?

**Comment by HamoBoker** [comment]
Yes @francescov1 , and sorry i forgot to close it.

Thank you for the amazing work 💙
