### ISSUE TITLE
Population broken at 4.3.5

### ISSUE THREAD

**Issue by kbariotis** [Automattic/mongoose#3753]
This piece of code stopped working after updating to 4.3.5, whilest the 4.3.4 works:

```js
return document
    .populate('videos.video', {is_archived: 0}, {is_archived: false})
    .populate('videos.pages_affected', {is_archived: 0 }, {is_archived: false})
    .execPopulate();
```

The returned document haven't been populated. `videos` is an array of documents, `videos.video` is a MongoID and `videos.pages_affected` is an array of MongoID's.

**Comment by vkarpov15** [comment]
Can you show schemas too please?

**Comment by kbariotis** [comment]
```js
var schema = new Schema({
    videos: [
        {
            video: {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'Video'
            },
            pages_affected: [
                {
                    type: mongoose.Schema.Types.ObjectId,
                    ref: 'ShopPage'
                }
            ]
        }
    ],
    is_archived: {
        type: Boolean,
        required: true
    }
}, {versionKey: false, strict: 'throw'});
```

**Comment by png262** [comment]
yes, i have same issue using 4.3.5 with execPopulate(). I am actually getting error saying that execPopulate() is not a function. Reverted to older version of Mongoose (4.0.7) and it works for same exact piece of code.
