### ISSUE TITLE
Make test failing due to changes in #2969

### ISSUE THREAD

**Issue by sybarite** [Automattic/mongoose#3673]
The commit added in #2969 rendered `make test` command to fail with the error message when you run make test for the first time. Steps to reproduce is to get a fresh copy of the repo and run `make test`

```
Error: Cannot find module 'type-component'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/vivekgounder/projects/javascript/mongoose/lib/schema/string.js:11:12)
....

The problem is at this line in `lib/schema/string.js`
``` javascript
var type = require('type-component');
```

I am removing this require as I could not find any references for the library in the package.json or the file in question itself. The Hotfix PR i am attaching with the issue is removing the offending line @vkarpov15 please make sure the removal does not add any more side effect?

Here is the PR Link https://github.com/Automattic/mongoose/pull/3674

**Comment by vkarpov15** [comment]
![image](https://cloud.githubusercontent.com/assets/1620265/11813858/8b5aad44-a311-11e5-9ed6-d9ac2b622aa0.png)

My bad

**Comment by sybarite** [comment]
@vkarpov15 Ah well it must have been one for those days for you :smile:
