### ISSUE TITLE
Update to 5.x.x breaks remove() on submodel-> remove().then is not a function

### ISSUE THREAD

**Issue by ofreese** [Automattic/mongoose#7381]
This works in 4.8.6

```
  let submodel = parentModel.arrayWithSubmodels.find(doc => doc._id == id)
  return submobdel.remove().then(doc => parentModel.save())
```

After changing it to 5.x.x that piece of code results in the error

> TypeError: doc.remove(...).then is not a function

When changing the version back to 4.8.6 it works again as expected

I can't find anything in the migration guide to this issue.
Is there any way to make it work in 5.x again?

**Comment by wulv5** [comment]
```
var test = mongoose.model('test', testSchema)
test.remove().then()

**Comment by vkarpov15** [comment]
Is there any reason why you can't do:

```javascript
  doc.children.find(c => c.name === 'test').remove();
  return doc.save();
```

instead? `remove()` on array subdocs was always synchronous, we just changed the API to not run middleware when you call `remove()` instead in 5.0.
