### ISSUE TITLE
Typescript does not detect precise types of Documents

### ISSUE THREAD

**Issue by maximedupre** [Automattic/mongoose#9726]
**Do you want to request a *feature* or report a *bug*?**
Regression bug

**What is the current behavior?**
See the comments I added at the end of lines that error

```
UserSchema.pre('save', async function (next) {
    const SALT_WORK_FACTOR = 10;

    if (!this.isModified('password')) return next();

    const salt = await bcrypt.genSalt(SALT_WORK_FACTOR);

    const hash = await bcrypt.hash(this.password, salt); // Property 'password' does not exist on type 'Document<any>'.

    this.password = hash; // Property 'password' does not exist on type 'Document<any>'.

    next();
});
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Was working in `v5.10.9` and does not work in `v5.11.8`

**Comment by vkarpov15** [comment]
Will be fixed in #9725, you'll be able to do:

```typescript
export interface UserDocument extends Document {
  password: string
}

const UserSchema = new Schema<UserDocument>(schemaDefinition);

UserSchema.pre('save', async function (next) {
    const SALT_WORK_FACTOR = 10;

    if (!this.isModified('password')) return next();

    const salt = await bcrypt.genSalt(SALT_WORK_FACTOR);

    const hash = await bcrypt.hash(this.password, salt); // Property 'password' does not exist on type 'Document<any>'.

    this.password = hash; // Property 'password' does not exist on type 'Document<any>'.

    next();
});

```
