### ISSUE TITLE
TypeError: this.$__schema.paths[p].splitPath is not a function

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10979]
When we upgraded to v6 from v5 we faced the exception below seemingly randomly, we can't consistently reproduce it.
I'll try to come up with a reproduction script.

The only thing I could find related to this error is #10453 which suggests that there are two versions of mongoose, even though that's not the case for me:
```
$ npm ls mongoose
├─┬ mongoose-cast-aggregation@0.2.1
│ └── mongoose@6.0.12 deduped
└── mongoose@6.0.12
```

```
TypeError: this.$__schema.paths[p].splitPath is not a function
    at model.Document.$__buildDoc (/root/speero-backend/node_modules/mongoose/lib/document.js:645:42)
    at model.Document (/root/speero-backend/node_modules/mongoose/lib/document.js:143:10)
    at model.Model (/root/speero-backend/node_modules/mongoose/lib/model.js:106:12)
    at new model (/root/speero-backend/node_modules/mongoose/lib/model.js:4763:15)
    at /root/speero-backend/node_modules/mongoose/lib/model.js:3112:22
    at /root/speero-backend/node_modules/mongoose/lib/model.js:3148:7
    at Array.forEach (<anonymous>)
    at /root/speero-backend/node_modules/mongoose/lib/model.js:3147:15
    at /root/speero-backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/root/speero-backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/root/speero-backend/node_modules/mongoose/lib/index.js:1151:10)
    at Function.create (/root/speero-backend/node_modules/mongoose/lib/model.js:3077:23)
    at Object.checkoutCart [as checkout] (file:///root/speero-backend/src/modules/carts/functions/carts.checkout.function.js:136:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by AbdelrahmanHafez** [comment]
I added a log to check when `splitPath` is not a function, the value of `this.$__schema.paths[p]` is
```
 { instance: 'ObjectID', options: { ref: 'CoreCity' } }
```

**Comment by AbdelrahmanHafez** [comment]
Turns out some piece of our code was modifying the schema by adding this POJO, it's not a mongoose error.
` { instance: 'ObjectID', options: { ref: 'CoreCity' } }`
