### ISSUE TITLE
Document does not implement addListener from EventEmitter

### ISSUE THREAD

**Issue by jthomerson** [Automattic/mongoose#2867]
I'm using Mongoose with [continuation-local-storage](https://www.npmjs.com/package/continuation-local-storage) so that I can have access to the current request user in the model's middleware for things like audit logging, etc. However, when upgrading from 3.8.0 to 4.0.1 CLS started complaining that a Document did not implement the EventEmitter API. Digging into the interaction between the two, it appears that this is caused by Document not implementing [addListener](https://nodejs.org/api/events.html#events_emitter_addlistener_event_listener).

This comes from the following commits:

 * def0afef
 * f299d9fb

I think all that needs to happen is that `addListener` needs to be added to the array of functions that end up getting added to Document's prototype. I'll try that and submit a PR if that works.

**Comment by vkarpov15** [comment]
Good catch. Yeah documents no longer inherit from EventEmitter because EE's have a lot of internal baggage and JS inheritance doesn't really let us hide that complexity very well.
