### ISSUE TITLE
(Bug) Type definitions: new signature for cursor.eachAsync() results in non-inferrable type arguments

### ISSUE THREAD

**Issue by lincolnthree** [Automattic/mongoose#10135]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

Upgraded: `mongoose  ^5.11.14  →  ^5.12.3`

After upgrading to 5.12.x, Compilation fails when using the `Cursor.eachAsync()` method with (previously) valid type arguments:

![image](https://user-images.githubusercontent.com/362329/114763613-fdfadf80-9d30-11eb-936d-b75ec53acc31.png)

![image](https://user-images.githubusercontent.com/362329/114763640-06531a80-9d31-11eb-8871-7495c9f7da6b.png)

```
Property 'id' does not exist on type '(TournamentResultSchemaV1 & Document<any, {}>) | [TournamentResultSchemaV1 & Document<any, {}>]'.
  Property 'id' does not exist on type '[TournamentResultSchemaV1 & Document<any, {}>]'.ts(2339)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Call the cursor API and attempt to reference an instance as a non-array type.

**What is the expected behavior?**

The type should be narrowed based on the method signature used. If not using batch processing, the type should not be an Array type (or an optional array type).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

5.12.3

This was changed in #9902 afaik, and results in a breaking API change as compilation fails with what used to be proper usage of the `eachAsync` API.

**Comment by lincolnthree** [comment]
Thank you @vkarpov15!
