### ISSUE TITLE
Migrating from @types/mongoose

### ISSUE THREAD

**Issue by SubJunk** [Automattic/mongoose#9721]
Hi, firstly I want to say thank you for this awesome library, and for including your own typings. It is a good idea for sure.

I have a project that isn't compiling after the 5.11 release, but it does work with 5.10 and @types/mongoose.
Last verified with 5.11.8. It is entirely possible that the problem is with our code and not yours. Any help would be greatly appreciated.

The PR to bump to 5.11.8 is at https://github.com/UniversalMediaServer/api/pull/358

One of the errors is:

```
    test/e2e/media.spec.ts:61:39 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type '{ directors: string[]; genres: string[]; imdbID: string; osdbHash: string; title: string; type: string; year: string; }' is not assignable to parameter of type 'MediaMetadataInterfaceDocument | _AllowStringsForIds<Pick<Pick<MediaMetadataInterfaceDocument, "_id" | "osdbHash" | "title" | ... 26 more ... | "votes">, "_id" | ... 28 more ... | "votes">>'.
          Type '{ directors: string[]; genres: string[]; imdbID: string; osdbHash: string; title: string; type: string; year: string; }' is missing the following properties from type '_AllowStringsForIds<Pick<Pick<MediaMetadataInterfaceDocument, "_id" | "osdbHash" | "title" | "type" | "year" | "createdAt" | "updatedAt" | "actors" | "awards" | "boxoffice" | ... 19 more ... | "votes">, "_id" | ... 28 more ... | "votes">>': createdAt, updatedAt, actors
    61       await MediaMetadataModel.create(interstellarMetaData);
                                             ~~~~~~~~~~~~~~~~~~~~
      node_modules/mongoose/index.d.ts:629:5
        629     create(...docs: Array<T | DocumentDefinition<T>>): Promise<T>;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        The last overload is declared here.
```

which you can hopefully view at https://travis-ci.org/github/UniversalMediaServer/api/builds/749741784#L266

The relevant typings are coming from https://github.com/UniversalMediaServer/api/blob/master/src/models/MediaMetadata.ts#L7 where we are defining our interface and then creating a version of it that extends Document. We did that initially to fix another types error. I'm not sure if that is the right thing to do so any guidance would be appreciated. Thank you

**Comment by AckerApple** [comment]
I can confirm having this issue as well.

Reverting to `5.10.19` works

Issue starts in `5.11.0`

**Comment by vkarpov15** [comment]
We will take a look at the errors, thanks for reporting.

**Comment by vkarpov15** [comment]
This issue looks like it's due to something in your `yarn.locl` file. I can run your tests successfully with `yarn test`, but the instant I remove your `yarn.lock` file and reinstall, or install using `npm`, I start getting the same errors locally with Mongoose v5.10 with `@types/mongoose`, not just Mongoose 5.11. For example:

```
      node_modules/@types/mongoose/index.d.ts:3315:5
        3315     create<TCreate = T>(...docs: CreateQuery<TCreate>[]): Promise<T>;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        The last overload is declared here.
    test/models/MediaMetadata.spec.ts:128:39 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type '{ directors: string[]; episodeNumber: string; genres: string[]; imdbID: string; osdbHash: string; searchMatches: string[]; seasonNumber: string; title: string; type: string; year: string; }' is not assignable to parameter of type 'Pick<{ rating?: string | number; goofs?: string; poster?: string; imdbID: string; osdbHash?: string; tagline?: string; title: string; trivia?: string; runtime?: string; type: string; year: string; votes?: string; ... 17 more ...; searchMatches?: string[]; } & { ...; }, "rating" | ... 27 more ... | "searchMatches"> &...'.
          Type '{ directors: string[]; episodeNumber: string; genres: string[]; imdbID: string; osdbHash: string; searchMatches: string[]; seasonNumber: string; title: string; type: string; year: string; }' is not assignable to type 'Pick<{ rating?: string | number; goofs?: string; poster?: string; imdbID: string; osdbHash?: string; tagline?: string; title: string; trivia?: string; runtime?: string; type: string; year: string; votes?: string; ... 17 more ...; searchMatches?: string[]; } & { ...; }, "rating" | ... 27 more ... | "searchMatches">'.

    128       await MediaMetadataModel.create(mediaMetaData);
                                              ~~~~~~~~~~~~~

      node_modules/@types/mongoose/index.d.ts:3315:5
        3315     create<TCreate = T>(...docs: CreateQuery<TCreate>[]): Promise<T>;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        The last overload is declared here.
```

The reason for this error is that, in some cases, like here: https://github.com/UniversalMediaServer/api/blob/46930a551c6cb6db7670c57a2b40983bbe32c34b/test/models/FailedLookups.spec.ts#L22 you're calling `create()` while explicitly omitting required fields. I don't know why removing `yarn.lock` changes this, it is likely that something changed in `@types/mongodb` that's causing this issue. Do you have any ideas @SubJunk ?

**Comment by SubJunk** [comment]
@vkarpov15 you're right, this was my fault for omitting required fields and some other problems, thank you! The question is really why did it ever work, and I don't know why that would be affected by the lockfile like this. I have fixed the problems and it is now passing.

Thanks again!

**Comment by AckerApple** [comment]
I was able to figure out that I had both `@types/mongoose` and `mongoose` installed.

I just removed the `@types/mongoose` dependency and all was fixed

**Comment by vkarpov15** [comment]
@SubJunk thanks for looking into this. I suspect there was something in your lockfile that was pegging an unexpected version. I don't think it was `@types/mongodb` or `@types/mongoose` because I tried updating those individually and the project still compiled... Regardless, glad the issue is fixed.

**Comment by zebralight** [comment]
hello. I updated from 5.11.8 to 5.11.11 and noticed that TypeScript isn't catching violations in `create`. For example, I have this ticket interface:
```
interface ITicket extends Document {
  title: string;
  price: number;
  userId: string;
  version?: number;
  orderId?: string;
}
```
and violating this by adding `foo` like so `const created = await Ticket.create({ title, price, userId, foo: "wef" });`  no longer issues an error as it did.

Highlighting over `create` on VS Code shows the following and includes the faulty `foo` property as if it's part of the interface:
```
(method) Model<ITicket>.create<{
    title: any;
    price: any;
    userId: string;
    foo: string;
}>(doc: {
    title: any;
    price: any;
    userId: string;
    foo: string;
}): Promise<ITicket> (+4 overloads)
```
Compilation works fine. It's just I'm now getting false negatives. I was wondering if I'm not typing anything in particular correctly or if it's something else.
Thank you!

**Comment by vkarpov15** [comment]
`const created = await Ticket.create({ title, price, userId, foo: "wef" });` is valid as far as Mongoose is concerned. By default, we would strip out the unknown property `foo` based on the [schema `strict` option](https://mongoosejs.com/docs/guide.html#strict).
