### ISSUE TITLE
typescript type for Model<T>.findByIdAndUpdate is missing overloads

### ISSUE THREAD

**Issue by tom-thorne** [Automattic/mongoose#9981]
After upgrading to 5.11.18 and adopting the built-in types instead of @types/mongoose, I find new type errors:

For example, 

Using...
mongoose: 5.11.18
typescript 4.2.2

**Expected behavior

```
 MyUserModel.findByIdAndUpdate(user._id, updates, function (err) {
    ...
    });
```

should give no compile error.

**Actual Behavior:

gives error:

```
error TS2769: No overload matches this call.
  Overload 1 of 3, '(id: any, update: UpdateQuery<IUser & Doc>, options: QueryOptions & { rawResult: true; }, callback?: (err: any, doc: FindAndModifyWriteOpResultObject<IUser & Doc>, res: any) => void): Query<...>', gave the following error.
    Argument of type '(updateErr: any) => void' is not assignable to parameter of type 'QueryOptions & { rawResult: true; }'.
      Property 'rawResult' is missing in type '(updateErr: any) => void' but required in type '{ rawResult: true; }'.
  Overload 2 of 3, '(id: any, update: UpdateQuery<IUser & Doc>, options: QueryOptions & { upsert: true; } & ReturnsNewDoc, callback?: (err: any, doc: IUser & Doc, res: any) => void): Query<...>', gave the following error.
    Argument of type '(updateErr: any) => void' is not assignable to parameter of type 'QueryOptions & { upsert: true; } & ReturnsNewDoc'.
      Type '(updateErr: any) => void' is not assignable to type 'QueryOptions & { upsert: true; } & { returnOriginal: false; }'.
        Property 'upsert' is missing in type '(updateErr: any) => void' but required in type '{ upsert: true; }'.
  Overload 3 of 3, '(id?: any, update?: UpdateQuery<IUser & Doc>, options?: QueryOptions, callback?: (err: any, doc: IUser & Doc, res: any) => void): Query<...>', gave the following error.
    Type '(updateErr: any) => void' has no properties in common with type 'QueryOptions'.
```

There is no overload defined with just 3 arguments...  from the mongoose lib comments these are the supported calls:

```
 * ####Examples:
 *
 *     A.findByIdAndUpdate(id, update, options, callback) // executes
 *     A.findByIdAndUpdate(id, update, options)  // returns Query
 *     A.findByIdAndUpdate(id, update, callback) // executes
 *     A.findByIdAndUpdate(id, update)           // returns Query
 *     A.findByIdAndUpdate()                     // returns Query
 ```

**Comment by FloodGames** [comment]
updateOne(
filter?: FilterQuery<T>, 
update?: UpdateQuery<T> | UpdateWithAggregationPipeline, 
options?: QueryOptions | null, 
callback?: (err: any, res: any)
 
 callback errorCheck is now the fourth parameter right?

**Comment by vkarpov15** [comment]
@FloodGames I don't understand the question, can you please clarify?

**Comment by lmwenda** [comment]
I am too experiencing this Easy. Can someone help?
