### ISSUE TITLE
model.findOne() returns type 'never' and Model type registered as 'undefined'

### ISSUE THREAD

**Issue by bradenmitchell** [Automattic/mongoose#10613]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using typescript, for methods such as model.findOne(), VSCode thinks the methods will return 'never'. Hence, subsequent use of the returned document throw errors that 'property/method does not exist on ...'

**If the current behavior is a bug, please provide the steps to reproduce.**

Step 1 - Create model with typings
```typescript
import mongoose from 'mongoose';

interface UserDocument extends mongoose.Document {
  email: string;
  password: string;
  verifyPassword: (candidate: string) => Promise<boolean>
};

interface UserModel extends mongoose.Model<UserDocument> {  };

const userSchema = new mongoose.Schema<UserDocument, UserModel>({
  email: String,
  password: String
});

userSchema.method('verifyPassword', async function(candidate: String): Promise<boolean> {
  // insert bcrypt compare function
})

export default mongoose.model('User', userSchema);
```

Step 2 - Use model in express route handler/controller
```typescript
import User from './User.model.ts';
import { Request, Response } from 'express';

export async function loginUserHandler(req: Request, res: Response) {
  const user = await User.findOne({ email: req.body.email }); // ERROR LINE 1

  if (!(await user.verifyPassword(req.body.password))) { // ERROR LINE 2
    next(new Error('Invalid login credentials'))
  }

  // remaining logic to create session/jwt etc...
}

```
Step 3 - See VSCode errors

In file created in step 2 above:
- hover over `await` in error line 1 and see warning `'await' has no effect on this type of expression`
- hover over `User` in error line 1 and see type of `const User: Model<UserDocument, undefined, any>` when it should be '<UserDocument, UserModel, any>'
- hover over `user` in error line 1 and see type of `const user: never`
- hover over `user.verifyPassword()` function in error line 2 and see error `Property verifyPassword does not exist on type of 'never'`

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "allowJs": true,
    "sourceMap": true,
    "outDir": "./build",
    "rootDir": "./src",
    "removeComments": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "coverage", "data"],
  "ts-node": {
    "transpileOnly": true
  }
}
```

**What is the expected behavior?**
`User.findOne()` should return type of `UserDocument | null` as in previous versions of mongoose.
Typing for `User` model should be `Model<UserDocument, UserModel, any>` not `<UserDocument, undefined, any>`

This bug appears to be present from version 5.13.7 (including current version 5.13.8). When I revert back to version 5.13.6 this bug is not present.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.17.3
Mongoose 5.13.8
MongoDB 3.6.10
Typescript 4.3.5

**Comment by vkarpov15** [comment]
I'm unable to repro this, the below script compiles fine with typescript@4.3.5, mongoose@5.13.8, and provided `compilerOptions`.

```typescript
import { model, Document, Model, Schema } from 'mongoose';

interface UserDocument extends Document {
  email: string;
  password: string;
  verifyPassword: (candidate: string) => Promise<boolean>
};

interface UserModel extends Model<UserDocument> {};

const userSchema = new Schema<UserDocument, UserModel>({
  email: String,
  password: String
});

userSchema.method('verifyPassword', async function(candidate: String): Promise<void> {
  // insert bcrypt compare function
})

const User = model('User', userSchema);

async function foo(): Promise<void> {
  const user: NonNullable<UserDocument> = await User.findOne({ email: 'test' }); // ERROR LINE 1
  
  if (!(await user.verifyPassword('test'))) { // ERROR LINE 2
    throw new Error('Invalid login credentials');
  }
}
```

I can assure you that `await User.findOne()` returns `UserDocument | null`, the relevant code is here: https://github.com/Automattic/mongoose/blob/5.13.8/index.d.ts#L885

I suspect the error is partially due to the `export default mongoose.model('User', userSchema)` line, should be `export default mongoose.model<UserDocument, UserModel>('User', userSchema)` to tell the `mongoose.model()` function to return `UserModel`.

**Comment by bradenmitchell** [comment]
I think you are right. Let's attribute this to user error rather than a bug - I'll close the issue.
I seem to be able to reproduce it, but when I export as `export default mongoose.model<UserDocument, UserModel>('User', userSchema)` as you suggest this works as expected.

**Comment by Asumoon** [comment]
Thank You :: Creating Interface helped me
