### ISSUE TITLE
TS Error: Types of property 'options' are incompatible in ChangeStream 

### ISSUE THREAD

**Issue by jamesweb1** [Automattic/mongoose#13605]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.3

### Node.js version

18.13

### MongoDB server version

5.7.0

### Typescript version (if applicable)

5.1.6

### Description

After updating the mongoose to v7.3.3 and mongodb to v5.7.0, it shows the error:

```
src/modules/device/device.service.ts:1621:5 - error TS2322: Type 'import("${PROJECT_HOME}/node/node_modules/mongoose/node_modules/mongodb/mongodb").ChangeStream<import("mongoose").Document<any, any, any>, any>' is not assignable to type 'import("${PROJECT_HOME}/node/node_modules/mongodb/mongodb").ChangeStream<import("mongoose").Document<any, any, any>, any>'.
  Types of property 'options' are incompatible.
    Type 'import("${PROJECT_HOME}/node/node_modules/mongoose/node_modules/mongodb/mongodb").ChangeStreamOptions & { writeConcern?: never; }' is not assignable to type 'import("${PROJECT_HOME}/node/node_modules/mongodb/mongodb").ChangeStreamOptions & { writeConcern?: never; }'.
      Type 'ChangeStreamOptions & { writeConcern?: never; }' is not assignable to type 'ChangeStreamOptions'.
        The types of 'session.clientOptions.autoEncrypter' are incompatible between these types.
          Type 'import("${PROJECT_HOME}/node/node_modules/mongoose/node_modules/mongodb/mongodb").AutoEncrypter' is not assignable to type 'import("${PROJECT_HOME}/node/node_modules/mongodb/mongodb").AutoEncrypter'.
            Types of parameters 'client' and 'client' are incompatible.
              Type 'import("${PROJECT_HOME}/node/node_modules/mongodb/mongodb").MongoClient' is not assignable to type 'import("${PROJECT_HOME}/node/node_modules/mongoose/node_modules/mongodb/mongodb").MongoClient'.
                The types of 'options.credentials' are incompatible between these types.
                  Type 'import("${PROJECT_HOME}/node/node_modules/mongodb/mongodb").MongoCredentials' is not assignable to type 'import("${PROJECT_HOME}/node/node_modules/mongoose/node_modules/mongodb/mongodb").MongoCredentials'.

1621     return stream;
```

### Steps to Reproduce

Here is the working example with (mongoose, mongodb) = (v6.3.2, v4.2.2)
```
import { Document, Model, ObjectId, Types } from 'mongoose';
import { ChangeStream } from 'mongodb';


deviceOnMongoChanged(
    onDeviceAdded: (device?: Device) => void,
  ): ChangeStream<Document> {
    const pipeline = [
      {
        $match: {
          $or: [
            { operationType: 'insert' },
            { operationType: 'delete' },
            {
              $and: [
                { operationType: 'update' },
                { 'updateDescription.updatedFields.groups': { $exists: true } },
              ],
            },
          ],
        },
      },
    ];

    const stream = this.deviceModel.watch<Document>(pipeline);
    stream
      .on('change', (next: MongoWatch) => {
        void (async () => {
          const device = await this.deviceModel.findById(next.documentKey);

          if (device) {
            onDeviceAdded(device);
          }

          if (next.operationType === 'delete') {
            onDeviceAdded(null);
          }
        })();
      })
      .on('error', (e) => {
        this.logger.error(e);
      });

    return stream;
  }
```

After updating the mongoose to v7.3.3 and mongodb to v5.7.0, it shows the error.

### Expected Behavior

I still can return the stream object as same as the previous code. It seems to be different typing for ChangeStream in mongodb and mongoose.

**Comment by IslandRhythms** [comment]
This script compiles no issue, please modify it to demonstrate your issue.

```typescript
import * as mongoose from 'mongoose';
import { ChangeStream } from 'mongodb';

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

function deviceOnMongoChanged(): ChangeStream<mongoose.Document> {
const pipeline = [
      {
        $match: {
          $or: [
            { operationType: 'insert' },
            { operationType: 'delete' },
            {
              $and: [
                { operationType: 'update' },
                { 'updateDescription.updatedFields.groups': { $exists: true } },
              ],
            },
          ],
        },
      },
    ];
const stream = Test.watch(pipeline);

stream.on('change', (res) => {
  void(async() => {
    const device = await Test.findById(res.documentKey);
    if (device) {
      // call a function
    }
    if (res.operationType === 'delete') {
      // call a function
    }
  })();
}).on('error', (e) => {
  console.log(e);
});

return stream;
}

deviceOnMongoChanged();
```
