### ISSUE TITLE
Update to mongoose 6.4.2 from 6.3.4 causing aggregate query to throw typescript error

### ISSUE THREAD

**Issue by Prashvith** [Automattic/mongoose#12050]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.2

### Node.js version

14.17

### MongoDB server version

4.6

### Description

On upgrate getting error in typescript compilation
error TS2769: No overload matches this call.
Aggregate query is 
query = [
		{ $match: { id: { $in: result.keys } } },
		{ $set: { __order: { $indexOfArray: [result.keys, '$id'] } } }
	];
$set is failing where the $indexOfArray expression is not accepted.

### Steps to Reproduce

Just call the aggregate method on the mongoose model with above query

### Expected Behavior

Query works correctly in version 6.3.4. Expect the same behaviour in 6.4.2

**Comment by vkarpov15** [comment]
@Prashvith I'm unable to repro, below script compiles fine with Mongoose 6.4.2. Can you please modify the below script to demonstrate the issue?

```ts
import mongoose from 'mongoose';
  
run().catch(err => console.log(err));

async function run() {
  const schema = new mongoose.Schema({ name: String });
  const Test = mongoose.model('Test', schema);

  await Test.aggregate([
    { $match: { id: { $in: ['foo'] } } },
    { $set: { __order: { $indexOfArray: [['foo'], '$id'] } } }
  ]);
} 
```
