### ISSUE TITLE
serverSelectionTimeoutMS and monitorCommands not valid properties in mongoose 6.2.0 after upgrading from 6.1.8

### ISSUE THREAD

**Issue by adieWilliams** [Automattic/mongoose#11324]
Our build is currently failing in CI/CD with:

```
error TS2345: Argument of type '{ bufferCommands: false; serverSelectionTimeoutMS: number; monitorCommands: boolean; }' is not assignable to parameter of type 'ConnectOptions'.

Object literal may only specify known properties, and 'serverSelectionTimeoutMS' does not exist in type 'ConnectOptions'.
```

Having done some digging it looks like this problem occurs in the upgrade between 6.1.8 and 6.2.0, I've checked the differences between the mongoose releases and there's no obvious cause.

Our project is using TypeScript with the following `tsconfig.json`:

``` json
{
  "compilerOptions": {
    "lib": ["es2017"],
    "removeComments": true,
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "target": "es2017",
    "outDir": "lib",
    "baseUrl": "./",
    "paths": {
      "@/constants/*": ["./constants/*"],
      "@/types/*": ["./types/*"],
      "@/libs/*": ["./libs/*"],
      "@/tests/*": ["./__tests__/*"]
    }
  },
  "include": ["./**/*.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ]
}
```

Node version 14.18.2

**Comment by IslandRhythms** [comment]
Can you provide the code causing the error?

**Comment by adieCodes** [comment]
It's within `connection` on the call to `createConnection` code:

``` ts
import { createConnection } from 'mongoose';
import * as schema from './schema';
import { BrandDocument } from '@/types/brand';

const DBURL = process.env.NODE_ENV === 'test' ? process.env.MONGO_URI : process.env.DBURL;
const CORE_DB = process.env.COREDB || 'core';

if (DBURL === 'undefined') throw new Error('Missing DB_URL env var');

export const connection = createConnection(DBURL, {
  bufferCommands: false,
  serverSelectionTimeoutMS: 5000,
  monitorCommands: true,
});

const coreDB = connection.useDb(CORE_DB);

connection.on('error', (e) => console.error(`DB error: ${e}`));

export const connect = async () => {
  await connection.asPromise();
};

export const disconnect = () => connection.close();
export const dropCoreDB = () => coreDB.dropDatabase();
export const dropAllDatabases = () => {
  Promise.all([connection.dropDatabase(), coreDB.dropDatabase()]);
};

export const Brand = coreDB.model<BrandDocument>('Brand', schema.Brand);

```

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';



const connection = mongoose.createConnection('mongodb://localhost:27017', {
  bufferCommands: false,
  serverSelectionTimeoutMS: 5000,
  monitorCommands: true,
});

const coreDB = connection.useDb('test');

connection.on('connected', () => {
  console.log('connected!')
});
connection.on('error', (e) => console.error(`DB error: ${e}`));

const connect = async () => {
  console.log('yo')
  await connection.asPromise();
};

const disconnect = () => connection.close();
const dropCoreDB = () => coreDB.dropDatabase();
const dropAllDatabases = () => {
  Promise.all([connection.dropDatabase(), coreDB.dropDatabase()]);
};

interface BrandDocument {
    name: string
}

const schema = new mongoose.Schema({
    name: String
})

const Brand = coreDB.model<BrandDocument>('Brand', schema);
connect();
console.log('done');
```

**Comment by Uzlopak** [comment]
The serverSelectionTimeoutMS is from mongodb native driver. We extend ConnectOption from the drivers typings. So it is not in our realm. I also don't see any change in the native driver and serverSelectionTimeoutMS was not removed.

**Comment by adieCodes** [comment]
Thanks both, it is a strange issue. There must be something in our project that's causing the issue in the package above 6.1.8

**Comment by adieWilliams** [comment]
This appears to be an issue with the v3 TypeScript, upgrading to v4 has resolved. Hope this is helpful for others
