### ISSUE TITLE
createWrapperSync is not a function

### ISSUE THREAD

**Issue by bitflower** [Automattic/mongoose#6229]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'm getting a `createWrapperSync is not a function` in this context after updating to 5.0.9 from 4.x:
```terminal
mongoose/lib/services/model/applyHooks.js:50
    createWrapperSync('init', objToDecorate.$__init, null, kareemOptions);
    ^

TypeError: schema.s.hooks.createWrapperSync is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have already uninstalled mongoose, checked `npm outdated` - all good. Nothing old around...

I found references to (https://github.com/vkarpov15/kareem/issues/12)[kareem 1]
and (https://github.com/cbargren/express-brute-mongoose/issues/12)[kareem 2].

Also in the migration path from 4 to 5 the init (https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md)[hook is mentioned]

Changing (https://github.com/Automattic/mongoose/blob/52cca5e9717e14292ca416ed18604a44d885abc6/lib/services/model/applyHooks.js#L50)[this line] to `createWrapper` fixes (? at least for me not checking the whole impact ....) the problem.

I'm using the plug `mongoose-unique-validator` on the schema:
```javascript
import * as uniqueValidator from 'mongoose-unique-validator';
SCHEMA.plugin(uniqueValidator);
```

**What is the expected behavior?**
Works as before ;-)

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.9.4
Mongoose 5.0.9
Mongo 3.6
macOS

**Comment by bitflower** [comment]
My mistake... in my own module which I was using over `npm link` (usually - but not today) ARGH :-) Sorry!
