### ISSUE TITLE
BREAKING CHANGE updating from `8.6.0` to `8.8.2`: `lean` query return full mongoose object type for populated doc instead of FlattenMaps

### ISSUE THREAD

**Issue by nikzanda** [Automattic/mongoose#15047]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.2

### Node.js version

20.10.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

5.5.4

### Description

In my repository, I have installed version `8.6.0` of Mongoose. After updating to the latest version (`8.8.2`), I encountered new typing errors: the PopulatedDoc variables are typed as full Mongoose objects instead of _FlattenMaps_ when the query is lean.

Below are some screenshots:

This is the type returned in version **8.6.0**:
![Image](https://github.com/user-attachments/assets/ac5dcad8-1cec-4e4e-977a-5832ed29cb05)

This is the type returned in version **8.8.2**:
![Image](https://github.com/user-attachments/assets/04e63889-8812-427e-bfe7-d4c91c0e829d)

Furthermore, for both versions of Mongoose, the linter does not give me any errors when I run `child.save()`, but at runtime, I get the expected error `child.save is not a function`.

![Image](https://github.com/user-attachments/assets/1e8a7340-22e3-4bec-971b-b81d387f1396)

As you can see from the screenshot, child is actually a normal object of type `IChild` (or `FlattenMaps<...>`), so it correctly throws an error when trying to execute `child.save()`. However, the linter should already be flagging this issue.
![Image](https://github.com/user-attachments/assets/9a270950-83cb-4322-88bd-7404bb0567f1)

### Steps to Reproduce

Reproduction link [here](https://stackblitz.com/edit/vitejs-vite-hpqjac?file=src%2Findex.ts)

### Expected Behavior

I expect `PopulatedDoc` variables to be typed with `IChild` or `FlattenMaps<...>` when the query is lean.

Ideally, `PopulatedDoc` variables should be directly typed with `FlattenMaps<...>` if the query uses the `populate` method, and with `Types.ObjectId` if the query does not use the `populate` method.

**Comment by mareksuscak** [comment]
8.7.2 specifically breaks this behavior. The last version that works is 8.7.1.

**Comment by vkarpov15** [comment]
This doesn't appear to be a breaking change, the following script compiles fine in 8.7.1, 8.7.2, 8.8.3, and 8.0.0:

```ts
import {
  connection,
  Document,
  HydratedDocument,
  Model,
  PopulatedDoc,
  Schema,
  SchemaTypes,
  Types,
} from 'mongoose';

interface IChild {
  _id: Types.ObjectId;
  name: string;
  createdAt: Date;
  updatedAt: Date;
}

type ChildDocumentOverrides = {};

interface IChildVirtuals {
  id: string;
}

type ChildInstance = HydratedDocument<
  IChild,
  ChildDocumentOverrides & IChildVirtuals
>;

type ChildModelType = Model<
  IChild,
  {},
  ChildDocumentOverrides,
  IChildVirtuals,
  ChildInstance
>;


const childSchema = new Schema<IChild, ChildModelType>(
  {
    name: {
      type: SchemaTypes.String,
      required: true,
      trim: true,
    },
  },
  {
    optimisticConcurrency: true,
    timestamps: true,
  }
);

interface IParent {
  _id: Types.ObjectId;
  name: string;
  child: PopulatedDoc<Document<Types.ObjectId> & IChild>;
  createdAt: Date;
  updatedAt: Date;
}

type ParentDocumentOverrides = {};

interface IParentVirtuals {
  id: string;
}

type ParentInstance = HydratedDocument<
  IParent,
  ParentDocumentOverrides & IParentVirtuals
>;

type ParentModelType = Model<
  IParent,
  {},
  ParentDocumentOverrides,
  IParentVirtuals,
  ParentInstance
>;

const parentSchema = new Schema<IParent, ParentModelType>(
  {
    name: {
      type: SchemaTypes.String,
      required: true,
      trim: true,
    },
    child: {
      type: SchemaTypes.ObjectId,
      ref: 'Child',
      required: true,
    },
  },
  { optimisticConcurrency: true, timestamps: true }
);

const main = async () => {
  console.log('prova');
  const ParentModel = connection.model<IParent, ParentModelType>(
    'Parent',
    parentSchema
  );
  const ChildModel = connection.model<IChild, ChildModelType>(
    'Child',
    childSchema
  );

  const newChild = await ChildModel.create({
    name: 'child 1',
  });
  console.log('newChild', newChild);

  const newParent = await ParentModel.create({
    name: 'parent 1',
    child: newChild,
  });
  console.log('newParent', newParent);

  const parent = await ParentModel.findById(newParent).populate('child').lean();
  if (parent) {
    const { child } = parent;
    console.log('child', child);
    if (child) {
      if (!(child instanceof Types.ObjectId)) {
        child.save();
      }
    }
  }
};

main();
```

Neither Mongoose 7 nor Mongoose 8 leans out PopulatedDoc, so I think this is expected behavior and consistent throughout recent Mongoose versions.

I would recommend updating your code to the following, which overrides the `child` type. This is how we typically recommend working with `populate()` in TypeScript anyway:

```ts
const parent = await ParentModel.findById(newParent).lean().populate<{ child: IChild }>('child');
```
