### ISSUE TITLE
TypeError: resolve is not a function 

### ISSUE THREAD

**Issue by gerhat** [Automattic/mongoose#9505]
In v5.10.10 I get the following error:
_TypeError: resolve is not a function at
node_modules/mongoose/lib/connection.js:814:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)_

Works fine with 5.10.9 and lower

My code is:
````js
const mongoose = require("mongoose");

const DB = mongoose.createConnection(process.env.DB, {
  useNewUrlParser: true,
  useCreateIndex: true,
  useFindAndModify: false,
  useUnifiedTopology: true,
});
````

**Comment by AbdelrahmanHafez** [comment]
Welcome @gerhat
Could you provide a reproduction script?

**Comment by gerhat** [comment]
Thank you @AbdelrahmanHafez.
Here is a small repo that reproduces the issue:
https://github.com/gerhat/mongoose-type-error-resolve

**Comment by AbdelrahmanHafez** [comment]
Thank you for providing a reproduction script, the issue is that `.then(...)` expects a function, and you're passing the value of invoking `console.log(...)` which is `undefined`.

To fix the issue, you need to change `testDB.then(console.log(`DB: connected`));` to `testDB.then(()=>console.log(`DB: connected`));` which will correctly log `DB: connected` only once the connection has been established.
