### ISSUE TITLE
RawDocType is not accessible trought  toObject/toJSON transform function anymore

### ISSUE THREAD

**Issue by PedroLucasHablla** [Automattic/mongoose#15521]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.16.2

### Node.js version

22.16.0

### MongoDB server version

7.0.21 Atlas

### Description

The #15501 PR introduced the ability to retrieve the `_id` and `__v` of a document from the `ret` parameter of the toObject/toJSON transform function. However, by doing so, the `RawDocType` is no longer accessible through the ret parameter, leading to a series of compilation errors when trying to access a document property, such as:

<img width="836" height="61" alt="Image" src="https://github.com/user-attachments/assets/95b617a7-7020-4e03-a749-bc3f41c071ee" />

### Steps to Reproduce

Try to access any document property over the `ret` parameter in the `transform()` function.

**Comment by vkarpov15** [comment]
The fact that your `RawDocType` only has `_id: unknown` is concerning, can you please provide a more complete repro script? For example, the following triggers a similar error:

```ts
import mongoose from 'mongoose';

const { Schema } = mongoose;

const schema = new Schema({
  name: { type: String, required: true }
}, {
  toObject: {
    transform(doc, ret) {
      ret.id = ret._id?.toString();
    }
  }
});
const TestModel = mongoose.model('Test', schema);
```

However the type is more correct in the error message: `error TS2339: Property 'id' does not exist on type 'FlatRecord<{ name: string; }> & { _id: ObjectId; } & { __v: number; }'.`

The only way Mongoose could fix the error in the above would be to once again make `ret` resolve to `any`. Otherwise, this is expected behavior in TypeScript: you can't assign arbitrary properties to objects. The more TypeScript-friendly approach is returning a new object as follows:

```ts
const schema = new Schema({
  name: { type: String, required: true }
}, {
  toObject: {
    transform(doc, ret) {
      return { ...ret, id: ret._id.toString() };
    }
  }
});
```

**Comment by PedroLucasHablla** [comment]
Thank you for the fast answer! It turns out that this was my fault from the beginning.

I didn't mentioned, but I'm using mongoose through NestJS. Here we define schemas by using decorators like this:

```js
@Schema({
  toJSON: {
    getters: true,
    virtuals: true,
    transform(doc, ret: any) {
      ret.workspace_id = ret.workspace?.toString() // was working on 8.13.2
      ret.id = ret._id?.toString(); // was working on 8.13.2
      ret.id = String(ret._id);
      delete ret._id;
      delete ret.__v;
    },
  },
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
})
export class Test {
  @Transform(({ value }) => value.toString())
  _id?: ObjectId;

  id?: string;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'Workspace' })
  workspace?: Workspace;

  @Prop({ type: String, required: true })
  name?: string;
}
```

What was going on is that when I declared the `tranform()` function, I didn't set the `ret` parameter as `any` in some of my schemas, that what was causing the compilation error on my end. This problem was not happening before `8.16.2`, that's why I thought that was a mongoose problem. That's just probably something weird happening on `@nestjs/mongoose` side.

Any way, thank you so much for the time answering this issue. I'll close it, but I'm happy to help if you'd like to investigate this further.
