### ISSUE TITLE
TS Linting error 4118 with schemas

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#13656]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.4

### Node.js version

19.7.0

### MongoDB server version

Atlas

### Typescript version (if applicable)

5.1.6, then 4.9.5

### Description

This seems to be more of a typescript issue, but it breaks the  schemas with a linting error.

I've been seeing this error in the past on my development machine, but it sort of "magically" went away after a few rebuild attempts. However, we have an experimental branch now and this fails our build system reliably. I suspect it's a TS issue, but weirdly enough, even after going back to 4.8.4, it still failed the build system (but resumed working on my machine after clearing all caches).

Have a look at the schema and error here (I'll add is as text at the end of this posting):

![image](https://github.com/Automattic/mongoose/assets/873009/0bd363b2-9b6b-4897-a19e-689eafa8f657)

Now, I can make this linting error on line 66 go away if I do one of the following:

- comment out line 68, OR
- make the array at line 63 a non-array, OR
- comment out lines 61/62

So basically: I don't see the pattern apart from the fact that it seems to fail my schema if there's some nesting involved.
It's probably related to typescript or typescript versions, but it fails at the lastest 5.x and 4.x versions for me.

Here's the schema code from the screenshot:

```
export const AccessRestrictionsSchema2 = new mongoose.Schema({
    // days: { type: [String], required: false },
}, { _id: false });

export const KeyRestrictionsSchema2 = new mongoose.Schema({
    validFrom: { type: Date, required: false, index: true },
    validTo: { type: Date, required: false, index: true },
    accessRestrictions: { type: [AccessRestrictionsSchema2], required: false },
}, { _id: false });

export const AuthorizationSetSchema = new mongoose.Schema({

    restrictions: { type: KeyRestrictionsSchema2, required: false },

});
```

### Steps to Reproduce

Hopefully by pasting the schema above, and potentially changing typescript versions. It's noteworthy that those exact schemas are happily compiling on our regular branches, and started failing only after some TS changes (but including reverting to 4.8.4).

**Comment by mstein** [comment]
I encountered the same error on some of my Schemas, moving from an 6.x version to the latest 7.4.1 version.
In my case, it seemed like we had an issue with an embedded schema `Date` field. If I changed the types of the field to `String` for example, it no longer trigger the error when compiling the typescript (on TS 5.1.6). I can confirm that on TS 4.7.x there is no problem, but I would prefer avoiding downgrading our TS version that far back...

Date fields at the root of the schema doesn't seems to trigger the error, but when embedded it no longer work for some reason, but is also not consistent accross all my schemas (I have schemas with embedded schemas with `Date` fields that don't seem to be problematic).

The "toPrimitive" field probably refers to [Date @@toPrimitive method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/@@toPrimitive). But I don't know what cause TS to trigger that error, only in specific situations.

**Comment by hardcodet** [comment]
As mentioned, it's not (only) Dates - the whole thing is super fuzzy. For example, while removing the two dates fixes it, I can also leave the date declarations and replace

`accessRestrictions: { type: [AccessRestrictionsSchema2], required: false },`

by this (make it a single document rather than an array):

`accessRestrictions: { type: AccessRestrictionsSchema2, required: false },`

This is super weird. I did also upgrade mongoose on the test branch from 6.x to 7.x, I'll revert this now.

**Comment by mstein** [comment]
Continuing with my experimentations, I found that creating a copy of the Schemas that triggered the error instead of using the existing Schema directly made the error disappear.

As an example, going from this
```typescript
const Schema1 = new Schema({ label: String, validatedAt: Date }, { _id: false })
const Schema2 = new Schema(
  {
    someField: String,
    embeddedVal: Schema1,
  },
  { _id: true, timestamp: false },
)
```

To this :
```typescript
const Schema1 = new Schema({ label: String, validatedAt: Date }, { _id: false })
const Schema2 = new Schema(
  {
    someField: String,
    embeddedVal: new Schema().add(Schema1) // << the change
  },
  { _id: true, timestamp: false },
)
```

did the trick.

We also had some places where we used `schema.clone()`, but if the original schema triggered the error, the cloned one would too. But using `new Schema().add(SchemaToClone)` instead would not trigger the error.

Since in v7.x of mongoose the `add()` method also copy the user defined schema options, it basically has the same result as a `clone()` in our use case.

So until this is fixed, we'll have to do with that workaround.

TypeScript 5.1.6
Mongoose 7.4.1

**Comment by vkarpov15** [comment]
Is there an error that occurs when you compile with tsc? Or is this just something that shows up in your IDE?

**Comment by hardcodet** [comment]
Yes, it causes a build error:

```
src/.../Data/Schemas.ts:119:14 - error TS4118: The type of this node cannot be serialized because its property '[toPrimitive]' cannot be serialized.

119 export const CredentialRestrictionsSchema = new mongoose.Schema({
```

**Comment by vkarpov15** [comment]
I've been trying to repro, but no luck. The following script compiles fine for me with `tsc --strict gh-13656.ts`  with TypeScript 5.1.6 and 4.8.4.

```ts
import mongoose from 'mongoose';

export const AccessRestrictionsSchema2 = new mongoose.Schema({
    days: { type: [String], required: false },
}, { _id: false });

export const KeyRestrictionsSchema2 = new mongoose.Schema({
    validFrom: { type: Date, required: false, index: true },
    validTo: { type: Date, required: false, index: true },
    accessRestrictions: { type: [AccessRestrictionsSchema2], required: false },
}, { _id: false });

export const AuthorizationSetSchema = new mongoose.Schema({

    restrictions: { type: KeyRestrictionsSchema2, required: false },

});
```

What does your `tsconfig.json` look like? Maybe some config setting is causing this.

**Comment by hardcodet** [comment]
Pity. I'm not sure this is worth spending too much time then. If it was a common issue, it would reflect here I guess.

In any case, here's our tsconfig:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2019",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true,
  },
  "exclude": ["node_modules", "dist"]
}
````

**Comment by mstein** [comment]
It seems to be a problem during the generation of the declaration file (the `declaration: true` option in the tsconfig. We also have this option in our tsconfig).

Can also be seen directly with `tsc --declaration gh-13656.ts` using the sample [used earlier](https://github.com/Automattic/mongoose/issues/13656#issuecomment-1664687737), I do get the error : 
```
error TS4118: The type of this node cannot be serialized because its property '[toPrimitive]' cannot be serialized.

13 export const AuthorizationSetSchema = new mongoose.Schema({
```

If I remove `declaration: true` from the tsconfig, I do not get an error.

_Env:_
OS: Windows 10
NodeJS: 18.17.0
TypeScript: 5.1.6
Mongoose: 7.4.2

**Comment by vkarpov15** [comment]
@mstein confirmed, although the issue only happens if strict mode is off :confused:  `tsc --declaration --strict gh-13656.ts` compiles fine. We're investigating to try to find a fix.

**Comment by vkarpov15** [comment]
I bisected this issue to v6.8.1. Relevant changes are #12784 and #12778. Here's the diff: https://github.com/Automattic/mongoose/compare/6.8.0...6.8.1 .

**Comment by vkarpov15** [comment]
Drilled down a little more and the following script is a better example:

```ts
import mongoose from 'mongoose';
  
export const AccessRestrictionsSchema2 = new mongoose.Schema({
    days: { type: [String], required: false },
}, { _id: false });

export const KeyRestrictionsSchema2 = new mongoose.Schema({
    validFrom: { type: Date, required: false, index: true },
    validTo: { type: Date, required: false, index: true },
    accessRestrictions: { type: [AccessRestrictionsSchema2], default: undefined, required: false },
}, { _id: false });

export const AuthorizationSetSchema = new mongoose.Schema({

    restrictions: { type: KeyRestrictionsSchema2, required: false },

});
```

Succeeds on 6.4.4, fails on 6.4.5. Diff: https://github.com/Automattic/mongoose/compare/6.4.4...6.4.5?diff=unified

**Comment by vkarpov15** [comment]
I've done a bunch of digging and the only thing I can come up with is that, for some reason, optional types in nested schemas trip up TypeScript with `declaration: true` and `strict: false`. I haven't been able to come up with a fix on Mongoose's end that doesn't involve dropping optional types altogether: for example, changing `OptionalPaths` from `[K in OptionalPathKeys<T, TypeKey>]?: T[K];` to `[K in OptionalPathKeys<T, TypeKey>]: T[K] | undefined;` makes this issue go away, but then of course we lose optional paths.

If you're running into this issue, there's 2 workarounds. First, enable strict mode. Second, explicitly overwrite the schema's document interface as follows. Overwriting the document interface isn't elegant, but it fixes the issue without changing TypeScript's strict mode.

```ts
import mongoose from 'mongoose';
  
export const AccessRestrictionsSchema2 = new mongoose.Schema({
    days: { type: [String], required: false },
}, { _id: false });

interface KeyRestrictionsType {
  validFrom?: Date;
  validTo?: Date;
  accessRestrictions?: { days?: string[] }[]
}

export const KeyRestrictionsSchema2 = new mongoose.Schema<KeyRestrictionsType>({
    validFrom: { type: Date, required: false, index: true },
    validTo: { type: Date, required: false, index: true },
    accessRestrictions: { type: [AccessRestrictionsSchema2], required: false },
}, { _id: false });

export const AuthorizationSetSchema = new mongoose.Schema({

    restrictions: { type: KeyRestrictionsSchema2, required: false },

});
```
