### ISSUE TITLE
`toObject` does not keep populated types

### ISSUE THREAD

**Issue by skrukwa** [Automattic/mongoose#16085]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

9.2.2

### Node.js version

24.13.1

### MongoDB server version

n/a

### Typescript version (if applicable)

5.8.3

### Description

calling `toObject` after `populate` does not keep the populated type in the plain object type

### Steps to Reproduce

```ts
const childSchema = new Schema({
    name: String
});
const Child = mongoose.model('Child', childSchema);

const parentSchema = new Schema({
    title: String,
    children: [{ type: Schema.Types.ObjectId, ref: 'Child' }]
});
const Parent = mongoose.model('Parent', parentSchema);

async function reproduce() {
    const parentDoc = new Parent({ title: 'My Parent', children: [] });

    const populatedDoc = await parentDoc.populate<{
        children: Types.DocumentArray<HydratedDocFromModel<typeof Child>>;
    }>('children');

    const childNameFromHydrated = populatedDoc.children[0]?.name; // OK

    const plainObject = populatedDoc.toObject();
    const childNameFromPlain = plainObject.children[0].name; // Property 'name' does not exist on type 'ObjectId'. ts(2339)
}
```

**Comment by skrukwa** [comment]
@vkarpov15 sorry for the follow up; can you confirm if `Types.DocumentArray` would be correct in the above example? I running into runtime `TypeError: populatedDoc. children.id is not a function`. (running `mongoose@9.2.4`)

I don't see any array examples in https://mongoosejs.com/docs/typescript/populate.html

**Comment by vkarpov15** [comment]
@skrukwa should be correct yes, the following script compiles fine in 9.4 branch

```ts
import mongoose from 'mongoose';

const { Schema } = mongoose;

const childSchema = new Schema({
    name: String
});
const Child = mongoose.model('Child', childSchema);

const parentSchema = new Schema({
    title: String,
    children: [{ type: Schema.Types.ObjectId, ref: 'Child' }]
});
const Parent = mongoose.model('Parent', parentSchema);

async function reproduce() {
    const parentDoc = new Parent({ title: 'My Parent', children: [] });

    const populatedDoc = await parentDoc.populate<{
        children: mongoose.Types.DocumentArray<mongoose.HydratedDocFromModel<typeof Child>>;
    }>('children');

    const childNameFromHydrated = populatedDoc.children[0]?.name; // OK

    const plainObject = populatedDoc.toObject();
    const childNameFromPlain = plainObject.children[0].name; // Property 'name' does not exist on type 'ObjectId'. ts(2339)
}

```

**Comment by skrukwa** [comment]
@vkarpov15 it is a runtime error that is thrown (not a typescript compilation error).

(just tried with 9.4 and still get the runtime error)

```ts
    const parentDoc = new Parent({ title: 'My Parent', children: [] });

    const childDoc = new Child({ name: 'My Child' });
    await childDoc.save();

    parentDoc.children.push(childDoc._id);
    await parentDoc.save();

    const populatedDoc = await parentDoc.populate<{
        children: mongoose.Types.DocumentArray<mongoose.HydratedDocFromModel<typeof Child>>;
    }>('children');

    const childNameFromHydrated = populatedDoc.children.id(childDoc._id)?.name; // COMIPLES FINE BUT THROWS RUNTIME ERROR
                                                                                // TypeError: populatedDoc.children.id is not a function
```
